# Distance Matrix

In [1]:
# imports
from sklearn import datasets
import numpy as np

In [3]:
# abstract
dataset = datasets.load_iris()

In [4]:
# dictionary
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [7]:
dataset["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
data = dataset["data"]
# data  # data is a numpy array data structure. Think of it as a matrix of data (or as an excel spreadsheet)

In [15]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
data.shape

(150, 4)

In [ ]:
# euclidean distance of 2 observations

In [12]:
# initialize distance matrix. What will be its final shape?
dist = sum((data[0]-data[1])**2)**(1/2)

In [13]:
print(dist)

0.5385164807134502


In [ ]:
# Build the distance matrix. Use 2 for loops, the append list method and the euclidean distance formula

In [24]:
dist=[]

In [17]:
for row1 in data:
    print(row1)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.2]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.6 1.4 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4

In [20]:
for row1 in data:
    for row2 in data:
        print(row1,row2)

[5.1 3.5 1.4 0.2] [5.1 3.5 1.4 0.2]
[5.1 3.5 1.4 0.2] [4.9 3.  1.4 0.2]
[5.1 3.5 1.4 0.2] [4.7 3.2 1.3 0.2]
[5.1 3.5 1.4 0.2] [4.6 3.1 1.5 0.2]
[5.1 3.5 1.4 0.2] [5.  3.6 1.4 0.2]
[5.1 3.5 1.4 0.2] [5.4 3.9 1.7 0.4]
[5.1 3.5 1.4 0.2] [4.6 3.4 1.4 0.3]
[5.1 3.5 1.4 0.2] [5.  3.4 1.5 0.2]
[5.1 3.5 1.4 0.2] [4.4 2.9 1.4 0.2]
[5.1 3.5 1.4 0.2] [4.9 3.1 1.5 0.1]
[5.1 3.5 1.4 0.2] [5.4 3.7 1.5 0.2]
[5.1 3.5 1.4 0.2] [4.8 3.4 1.6 0.2]
[5.1 3.5 1.4 0.2] [4.8 3.  1.4 0.1]
[5.1 3.5 1.4 0.2] [4.3 3.  1.1 0.1]
[5.1 3.5 1.4 0.2] [5.8 4.  1.2 0.2]
[5.1 3.5 1.4 0.2] [5.7 4.4 1.5 0.4]
[5.1 3.5 1.4 0.2] [5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.2] [5.1 3.5 1.4 0.3]
[5.1 3.5 1.4 0.2] [5.7 3.8 1.7 0.3]
[5.1 3.5 1.4 0.2] [5.1 3.8 1.5 0.3]
[5.1 3.5 1.4 0.2] [5.4 3.4 1.7 0.2]
[5.1 3.5 1.4 0.2] [5.1 3.7 1.5 0.4]
[5.1 3.5 1.4 0.2] [4.6 3.6 1.  0.2]
[5.1 3.5 1.4 0.2] [5.1 3.3 1.7 0.5]
[5.1 3.5 1.4 0.2] [4.8 3.4 1.9 0.2]
[5.1 3.5 1.4 0.2] [5.  3.  1.6 0.2]
[5.1 3.5 1.4 0.2] [5.  3.4 1.6 0.4]
[5.1 3.5 1.4 0.2] [5.2 3.5 1

[4.6 3.1 1.5 0.2] [6.  3.  4.8 1.8]
[4.6 3.1 1.5 0.2] [6.9 3.1 5.4 2.1]
[4.6 3.1 1.5 0.2] [6.7 3.1 5.6 2.4]
[4.6 3.1 1.5 0.2] [6.9 3.1 5.1 2.3]
[4.6 3.1 1.5 0.2] [5.8 2.7 5.1 1.9]
[4.6 3.1 1.5 0.2] [6.8 3.2 5.9 2.3]
[4.6 3.1 1.5 0.2] [6.7 3.3 5.7 2.5]
[4.6 3.1 1.5 0.2] [6.7 3.  5.2 2.3]
[4.6 3.1 1.5 0.2] [6.3 2.5 5.  1.9]
[4.6 3.1 1.5 0.2] [6.5 3.  5.2 2. ]
[4.6 3.1 1.5 0.2] [6.2 3.4 5.4 2.3]
[4.6 3.1 1.5 0.2] [5.9 3.  5.1 1.8]
[5.  3.6 1.4 0.2] [5.1 3.5 1.4 0.2]
[5.  3.6 1.4 0.2] [4.9 3.  1.4 0.2]
[5.  3.6 1.4 0.2] [4.7 3.2 1.3 0.2]
[5.  3.6 1.4 0.2] [4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2] [5.  3.6 1.4 0.2]
[5.  3.6 1.4 0.2] [5.4 3.9 1.7 0.4]
[5.  3.6 1.4 0.2] [4.6 3.4 1.4 0.3]
[5.  3.6 1.4 0.2] [5.  3.4 1.5 0.2]
[5.  3.6 1.4 0.2] [4.4 2.9 1.4 0.2]
[5.  3.6 1.4 0.2] [4.9 3.1 1.5 0.1]
[5.  3.6 1.4 0.2] [5.4 3.7 1.5 0.2]
[5.  3.6 1.4 0.2] [4.8 3.4 1.6 0.2]
[5.  3.6 1.4 0.2] [4.8 3.  1.4 0.1]
[5.  3.6 1.4 0.2] [4.3 3.  1.1 0.1]
[5.  3.6 1.4 0.2] [5.8 4.  1.2 0.2]
[5.  3.6 1.4 0.2] [5.7 4.4 1

[5.  3.4 1.5 0.2] [4.9 3.6 1.4 0.1]
[5.  3.4 1.5 0.2] [4.4 3.  1.3 0.2]
[5.  3.4 1.5 0.2] [5.1 3.4 1.5 0.2]
[5.  3.4 1.5 0.2] [5.  3.5 1.3 0.3]
[5.  3.4 1.5 0.2] [4.5 2.3 1.3 0.3]
[5.  3.4 1.5 0.2] [4.4 3.2 1.3 0.2]
[5.  3.4 1.5 0.2] [5.  3.5 1.6 0.6]
[5.  3.4 1.5 0.2] [5.1 3.8 1.9 0.4]
[5.  3.4 1.5 0.2] [4.8 3.  1.4 0.3]
[5.  3.4 1.5 0.2] [5.1 3.8 1.6 0.2]
[5.  3.4 1.5 0.2] [4.6 3.2 1.4 0.2]
[5.  3.4 1.5 0.2] [5.3 3.7 1.5 0.2]
[5.  3.4 1.5 0.2] [5.  3.3 1.4 0.2]
[5.  3.4 1.5 0.2] [7.  3.2 4.7 1.4]
[5.  3.4 1.5 0.2] [6.4 3.2 4.5 1.5]
[5.  3.4 1.5 0.2] [6.9 3.1 4.9 1.5]
[5.  3.4 1.5 0.2] [5.5 2.3 4.  1.3]
[5.  3.4 1.5 0.2] [6.5 2.8 4.6 1.5]
[5.  3.4 1.5 0.2] [5.7 2.8 4.5 1.3]
[5.  3.4 1.5 0.2] [6.3 3.3 4.7 1.6]
[5.  3.4 1.5 0.2] [4.9 2.4 3.3 1. ]
[5.  3.4 1.5 0.2] [6.6 2.9 4.6 1.3]
[5.  3.4 1.5 0.2] [5.2 2.7 3.9 1.4]
[5.  3.4 1.5 0.2] [5.  2.  3.5 1. ]
[5.  3.4 1.5 0.2] [5.9 3.  4.2 1.5]
[5.  3.4 1.5 0.2] [6.  2.2 4.  1. ]
[5.  3.4 1.5 0.2] [6.1 2.9 4.7 1.4]
[5.  3.4 1.5 0.2] [5.6 2.9 3

[5.4 3.7 1.5 0.2] [6.3 2.3 4.4 1.3]
[5.4 3.7 1.5 0.2] [5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2] [5.5 2.5 4.  1.3]
[5.4 3.7 1.5 0.2] [5.5 2.6 4.4 1.2]
[5.4 3.7 1.5 0.2] [6.1 3.  4.6 1.4]
[5.4 3.7 1.5 0.2] [5.8 2.6 4.  1.2]
[5.4 3.7 1.5 0.2] [5.  2.3 3.3 1. ]
[5.4 3.7 1.5 0.2] [5.6 2.7 4.2 1.3]
[5.4 3.7 1.5 0.2] [5.7 3.  4.2 1.2]
[5.4 3.7 1.5 0.2] [5.7 2.9 4.2 1.3]
[5.4 3.7 1.5 0.2] [6.2 2.9 4.3 1.3]
[5.4 3.7 1.5 0.2] [5.1 2.5 3.  1.1]
[5.4 3.7 1.5 0.2] [5.7 2.8 4.1 1.3]
[5.4 3.7 1.5 0.2] [6.3 3.3 6.  2.5]
[5.4 3.7 1.5 0.2] [5.8 2.7 5.1 1.9]
[5.4 3.7 1.5 0.2] [7.1 3.  5.9 2.1]
[5.4 3.7 1.5 0.2] [6.3 2.9 5.6 1.8]
[5.4 3.7 1.5 0.2] [6.5 3.  5.8 2.2]
[5.4 3.7 1.5 0.2] [7.6 3.  6.6 2.1]
[5.4 3.7 1.5 0.2] [4.9 2.5 4.5 1.7]
[5.4 3.7 1.5 0.2] [7.3 2.9 6.3 1.8]
[5.4 3.7 1.5 0.2] [6.7 2.5 5.8 1.8]
[5.4 3.7 1.5 0.2] [7.2 3.6 6.1 2.5]
[5.4 3.7 1.5 0.2] [6.5 3.2 5.1 2. ]
[5.4 3.7 1.5 0.2] [6.4 2.7 5.3 1.9]
[5.4 3.7 1.5 0.2] [6.8 3.  5.5 2.1]
[5.4 3.7 1.5 0.2] [5.7 2.5 5.  2. ]
[5.4 3.7 1.5 0.2] [5.8 2.8 5

[4.3 3.  1.1 0.1] [6.4 3.1 5.5 1.8]
[4.3 3.  1.1 0.1] [6.  3.  4.8 1.8]
[4.3 3.  1.1 0.1] [6.9 3.1 5.4 2.1]
[4.3 3.  1.1 0.1] [6.7 3.1 5.6 2.4]
[4.3 3.  1.1 0.1] [6.9 3.1 5.1 2.3]
[4.3 3.  1.1 0.1] [5.8 2.7 5.1 1.9]
[4.3 3.  1.1 0.1] [6.8 3.2 5.9 2.3]
[4.3 3.  1.1 0.1] [6.7 3.3 5.7 2.5]
[4.3 3.  1.1 0.1] [6.7 3.  5.2 2.3]
[4.3 3.  1.1 0.1] [6.3 2.5 5.  1.9]
[4.3 3.  1.1 0.1] [6.5 3.  5.2 2. ]
[4.3 3.  1.1 0.1] [6.2 3.4 5.4 2.3]
[4.3 3.  1.1 0.1] [5.9 3.  5.1 1.8]
[5.8 4.  1.2 0.2] [5.1 3.5 1.4 0.2]
[5.8 4.  1.2 0.2] [4.9 3.  1.4 0.2]
[5.8 4.  1.2 0.2] [4.7 3.2 1.3 0.2]
[5.8 4.  1.2 0.2] [4.6 3.1 1.5 0.2]
[5.8 4.  1.2 0.2] [5.  3.6 1.4 0.2]
[5.8 4.  1.2 0.2] [5.4 3.9 1.7 0.4]
[5.8 4.  1.2 0.2] [4.6 3.4 1.4 0.3]
[5.8 4.  1.2 0.2] [5.  3.4 1.5 0.2]
[5.8 4.  1.2 0.2] [4.4 2.9 1.4 0.2]
[5.8 4.  1.2 0.2] [4.9 3.1 1.5 0.1]
[5.8 4.  1.2 0.2] [5.4 3.7 1.5 0.2]
[5.8 4.  1.2 0.2] [4.8 3.4 1.6 0.2]
[5.8 4.  1.2 0.2] [4.8 3.  1.4 0.1]
[5.8 4.  1.2 0.2] [4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2] [5.8 4.  1

[5.1 3.5 1.4 0.3] [4.9 3.6 1.4 0.1]
[5.1 3.5 1.4 0.3] [4.4 3.  1.3 0.2]
[5.1 3.5 1.4 0.3] [5.1 3.4 1.5 0.2]
[5.1 3.5 1.4 0.3] [5.  3.5 1.3 0.3]
[5.1 3.5 1.4 0.3] [4.5 2.3 1.3 0.3]
[5.1 3.5 1.4 0.3] [4.4 3.2 1.3 0.2]
[5.1 3.5 1.4 0.3] [5.  3.5 1.6 0.6]
[5.1 3.5 1.4 0.3] [5.1 3.8 1.9 0.4]
[5.1 3.5 1.4 0.3] [4.8 3.  1.4 0.3]
[5.1 3.5 1.4 0.3] [5.1 3.8 1.6 0.2]
[5.1 3.5 1.4 0.3] [4.6 3.2 1.4 0.2]
[5.1 3.5 1.4 0.3] [5.3 3.7 1.5 0.2]
[5.1 3.5 1.4 0.3] [5.  3.3 1.4 0.2]
[5.1 3.5 1.4 0.3] [7.  3.2 4.7 1.4]
[5.1 3.5 1.4 0.3] [6.4 3.2 4.5 1.5]
[5.1 3.5 1.4 0.3] [6.9 3.1 4.9 1.5]
[5.1 3.5 1.4 0.3] [5.5 2.3 4.  1.3]
[5.1 3.5 1.4 0.3] [6.5 2.8 4.6 1.5]
[5.1 3.5 1.4 0.3] [5.7 2.8 4.5 1.3]
[5.1 3.5 1.4 0.3] [6.3 3.3 4.7 1.6]
[5.1 3.5 1.4 0.3] [4.9 2.4 3.3 1. ]
[5.1 3.5 1.4 0.3] [6.6 2.9 4.6 1.3]
[5.1 3.5 1.4 0.3] [5.2 2.7 3.9 1.4]
[5.1 3.5 1.4 0.3] [5.  2.  3.5 1. ]
[5.1 3.5 1.4 0.3] [5.9 3.  4.2 1.5]
[5.1 3.5 1.4 0.3] [6.  2.2 4.  1. ]
[5.1 3.5 1.4 0.3] [6.1 2.9 4.7 1.4]
[5.1 3.5 1.4 0.3] [5.6 2.9 3

[5.4 3.4 1.7 0.2] [6.7 3.1 4.7 1.5]
[5.4 3.4 1.7 0.2] [6.3 2.3 4.4 1.3]
[5.4 3.4 1.7 0.2] [5.6 3.  4.1 1.3]
[5.4 3.4 1.7 0.2] [5.5 2.5 4.  1.3]
[5.4 3.4 1.7 0.2] [5.5 2.6 4.4 1.2]
[5.4 3.4 1.7 0.2] [6.1 3.  4.6 1.4]
[5.4 3.4 1.7 0.2] [5.8 2.6 4.  1.2]
[5.4 3.4 1.7 0.2] [5.  2.3 3.3 1. ]
[5.4 3.4 1.7 0.2] [5.6 2.7 4.2 1.3]
[5.4 3.4 1.7 0.2] [5.7 3.  4.2 1.2]
[5.4 3.4 1.7 0.2] [5.7 2.9 4.2 1.3]
[5.4 3.4 1.7 0.2] [6.2 2.9 4.3 1.3]
[5.4 3.4 1.7 0.2] [5.1 2.5 3.  1.1]
[5.4 3.4 1.7 0.2] [5.7 2.8 4.1 1.3]
[5.4 3.4 1.7 0.2] [6.3 3.3 6.  2.5]
[5.4 3.4 1.7 0.2] [5.8 2.7 5.1 1.9]
[5.4 3.4 1.7 0.2] [7.1 3.  5.9 2.1]
[5.4 3.4 1.7 0.2] [6.3 2.9 5.6 1.8]
[5.4 3.4 1.7 0.2] [6.5 3.  5.8 2.2]
[5.4 3.4 1.7 0.2] [7.6 3.  6.6 2.1]
[5.4 3.4 1.7 0.2] [4.9 2.5 4.5 1.7]
[5.4 3.4 1.7 0.2] [7.3 2.9 6.3 1.8]
[5.4 3.4 1.7 0.2] [6.7 2.5 5.8 1.8]
[5.4 3.4 1.7 0.2] [7.2 3.6 6.1 2.5]
[5.4 3.4 1.7 0.2] [6.5 3.2 5.1 2. ]
[5.4 3.4 1.7 0.2] [6.4 2.7 5.3 1.9]
[5.4 3.4 1.7 0.2] [6.8 3.  5.5 2.1]
[5.4 3.4 1.7 0.2] [5.7 2.5 5

[5.1 3.3 1.7 0.5] [6.3 3.4 5.6 2.4]
[5.1 3.3 1.7 0.5] [6.4 3.1 5.5 1.8]
[5.1 3.3 1.7 0.5] [6.  3.  4.8 1.8]
[5.1 3.3 1.7 0.5] [6.9 3.1 5.4 2.1]
[5.1 3.3 1.7 0.5] [6.7 3.1 5.6 2.4]
[5.1 3.3 1.7 0.5] [6.9 3.1 5.1 2.3]
[5.1 3.3 1.7 0.5] [5.8 2.7 5.1 1.9]
[5.1 3.3 1.7 0.5] [6.8 3.2 5.9 2.3]
[5.1 3.3 1.7 0.5] [6.7 3.3 5.7 2.5]
[5.1 3.3 1.7 0.5] [6.7 3.  5.2 2.3]
[5.1 3.3 1.7 0.5] [6.3 2.5 5.  1.9]
[5.1 3.3 1.7 0.5] [6.5 3.  5.2 2. ]
[5.1 3.3 1.7 0.5] [6.2 3.4 5.4 2.3]
[5.1 3.3 1.7 0.5] [5.9 3.  5.1 1.8]
[4.8 3.4 1.9 0.2] [5.1 3.5 1.4 0.2]
[4.8 3.4 1.9 0.2] [4.9 3.  1.4 0.2]
[4.8 3.4 1.9 0.2] [4.7 3.2 1.3 0.2]
[4.8 3.4 1.9 0.2] [4.6 3.1 1.5 0.2]
[4.8 3.4 1.9 0.2] [5.  3.6 1.4 0.2]
[4.8 3.4 1.9 0.2] [5.4 3.9 1.7 0.4]
[4.8 3.4 1.9 0.2] [4.6 3.4 1.4 0.3]
[4.8 3.4 1.9 0.2] [5.  3.4 1.5 0.2]
[4.8 3.4 1.9 0.2] [4.4 2.9 1.4 0.2]
[4.8 3.4 1.9 0.2] [4.9 3.1 1.5 0.1]
[4.8 3.4 1.9 0.2] [5.4 3.7 1.5 0.2]
[4.8 3.4 1.9 0.2] [4.8 3.4 1.6 0.2]
[4.8 3.4 1.9 0.2] [4.8 3.  1.4 0.1]
[4.8 3.4 1.9 0.2] [4.3 3.  1

[5.2 3.5 1.5 0.2] [5.5 3.5 1.3 0.2]
[5.2 3.5 1.5 0.2] [4.9 3.6 1.4 0.1]
[5.2 3.5 1.5 0.2] [4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2] [5.1 3.4 1.5 0.2]
[5.2 3.5 1.5 0.2] [5.  3.5 1.3 0.3]
[5.2 3.5 1.5 0.2] [4.5 2.3 1.3 0.3]
[5.2 3.5 1.5 0.2] [4.4 3.2 1.3 0.2]
[5.2 3.5 1.5 0.2] [5.  3.5 1.6 0.6]
[5.2 3.5 1.5 0.2] [5.1 3.8 1.9 0.4]
[5.2 3.5 1.5 0.2] [4.8 3.  1.4 0.3]
[5.2 3.5 1.5 0.2] [5.1 3.8 1.6 0.2]
[5.2 3.5 1.5 0.2] [4.6 3.2 1.4 0.2]
[5.2 3.5 1.5 0.2] [5.3 3.7 1.5 0.2]
[5.2 3.5 1.5 0.2] [5.  3.3 1.4 0.2]
[5.2 3.5 1.5 0.2] [7.  3.2 4.7 1.4]
[5.2 3.5 1.5 0.2] [6.4 3.2 4.5 1.5]
[5.2 3.5 1.5 0.2] [6.9 3.1 4.9 1.5]
[5.2 3.5 1.5 0.2] [5.5 2.3 4.  1.3]
[5.2 3.5 1.5 0.2] [6.5 2.8 4.6 1.5]
[5.2 3.5 1.5 0.2] [5.7 2.8 4.5 1.3]
[5.2 3.5 1.5 0.2] [6.3 3.3 4.7 1.6]
[5.2 3.5 1.5 0.2] [4.9 2.4 3.3 1. ]
[5.2 3.5 1.5 0.2] [6.6 2.9 4.6 1.3]
[5.2 3.5 1.5 0.2] [5.2 2.7 3.9 1.4]
[5.2 3.5 1.5 0.2] [5.  2.  3.5 1. ]
[5.2 3.5 1.5 0.2] [5.9 3.  4.2 1.5]
[5.2 3.5 1.5 0.2] [6.  2.2 4.  1. ]
[5.2 3.5 1.5 0.2] [6.1 2.9 4

[4.8 3.1 1.6 0.2] [6.7 3.1 4.7 1.5]
[4.8 3.1 1.6 0.2] [6.3 2.3 4.4 1.3]
[4.8 3.1 1.6 0.2] [5.6 3.  4.1 1.3]
[4.8 3.1 1.6 0.2] [5.5 2.5 4.  1.3]
[4.8 3.1 1.6 0.2] [5.5 2.6 4.4 1.2]
[4.8 3.1 1.6 0.2] [6.1 3.  4.6 1.4]
[4.8 3.1 1.6 0.2] [5.8 2.6 4.  1.2]
[4.8 3.1 1.6 0.2] [5.  2.3 3.3 1. ]
[4.8 3.1 1.6 0.2] [5.6 2.7 4.2 1.3]
[4.8 3.1 1.6 0.2] [5.7 3.  4.2 1.2]
[4.8 3.1 1.6 0.2] [5.7 2.9 4.2 1.3]
[4.8 3.1 1.6 0.2] [6.2 2.9 4.3 1.3]
[4.8 3.1 1.6 0.2] [5.1 2.5 3.  1.1]
[4.8 3.1 1.6 0.2] [5.7 2.8 4.1 1.3]
[4.8 3.1 1.6 0.2] [6.3 3.3 6.  2.5]
[4.8 3.1 1.6 0.2] [5.8 2.7 5.1 1.9]
[4.8 3.1 1.6 0.2] [7.1 3.  5.9 2.1]
[4.8 3.1 1.6 0.2] [6.3 2.9 5.6 1.8]
[4.8 3.1 1.6 0.2] [6.5 3.  5.8 2.2]
[4.8 3.1 1.6 0.2] [7.6 3.  6.6 2.1]
[4.8 3.1 1.6 0.2] [4.9 2.5 4.5 1.7]
[4.8 3.1 1.6 0.2] [7.3 2.9 6.3 1.8]
[4.8 3.1 1.6 0.2] [6.7 2.5 5.8 1.8]
[4.8 3.1 1.6 0.2] [7.2 3.6 6.1 2.5]
[4.8 3.1 1.6 0.2] [6.5 3.2 5.1 2. ]
[4.8 3.1 1.6 0.2] [6.4 2.7 5.3 1.9]
[4.8 3.1 1.6 0.2] [6.8 3.  5.5 2.1]
[4.8 3.1 1.6 0.2] [5.7 2.5 5

[5.5 4.2 1.4 0.2] [7.7 3.  6.1 2.3]
[5.5 4.2 1.4 0.2] [6.3 3.4 5.6 2.4]
[5.5 4.2 1.4 0.2] [6.4 3.1 5.5 1.8]
[5.5 4.2 1.4 0.2] [6.  3.  4.8 1.8]
[5.5 4.2 1.4 0.2] [6.9 3.1 5.4 2.1]
[5.5 4.2 1.4 0.2] [6.7 3.1 5.6 2.4]
[5.5 4.2 1.4 0.2] [6.9 3.1 5.1 2.3]
[5.5 4.2 1.4 0.2] [5.8 2.7 5.1 1.9]
[5.5 4.2 1.4 0.2] [6.8 3.2 5.9 2.3]
[5.5 4.2 1.4 0.2] [6.7 3.3 5.7 2.5]
[5.5 4.2 1.4 0.2] [6.7 3.  5.2 2.3]
[5.5 4.2 1.4 0.2] [6.3 2.5 5.  1.9]
[5.5 4.2 1.4 0.2] [6.5 3.  5.2 2. ]
[5.5 4.2 1.4 0.2] [6.2 3.4 5.4 2.3]
[5.5 4.2 1.4 0.2] [5.9 3.  5.1 1.8]
[4.9 3.1 1.5 0.2] [5.1 3.5 1.4 0.2]
[4.9 3.1 1.5 0.2] [4.9 3.  1.4 0.2]
[4.9 3.1 1.5 0.2] [4.7 3.2 1.3 0.2]
[4.9 3.1 1.5 0.2] [4.6 3.1 1.5 0.2]
[4.9 3.1 1.5 0.2] [5.  3.6 1.4 0.2]
[4.9 3.1 1.5 0.2] [5.4 3.9 1.7 0.4]
[4.9 3.1 1.5 0.2] [4.6 3.4 1.4 0.3]
[4.9 3.1 1.5 0.2] [5.  3.4 1.5 0.2]
[4.9 3.1 1.5 0.2] [4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.2] [4.9 3.1 1.5 0.1]
[4.9 3.1 1.5 0.2] [5.4 3.7 1.5 0.2]
[4.9 3.1 1.5 0.2] [4.8 3.4 1.6 0.2]
[4.9 3.1 1.5 0.2] [4.8 3.  1

[4.9 3.6 1.4 0.1] [4.8 3.1 1.6 0.2]
[4.9 3.6 1.4 0.1] [5.4 3.4 1.5 0.4]
[4.9 3.6 1.4 0.1] [5.2 4.1 1.5 0.1]
[4.9 3.6 1.4 0.1] [5.5 4.2 1.4 0.2]
[4.9 3.6 1.4 0.1] [4.9 3.1 1.5 0.2]
[4.9 3.6 1.4 0.1] [5.  3.2 1.2 0.2]
[4.9 3.6 1.4 0.1] [5.5 3.5 1.3 0.2]
[4.9 3.6 1.4 0.1] [4.9 3.6 1.4 0.1]
[4.9 3.6 1.4 0.1] [4.4 3.  1.3 0.2]
[4.9 3.6 1.4 0.1] [5.1 3.4 1.5 0.2]
[4.9 3.6 1.4 0.1] [5.  3.5 1.3 0.3]
[4.9 3.6 1.4 0.1] [4.5 2.3 1.3 0.3]
[4.9 3.6 1.4 0.1] [4.4 3.2 1.3 0.2]
[4.9 3.6 1.4 0.1] [5.  3.5 1.6 0.6]
[4.9 3.6 1.4 0.1] [5.1 3.8 1.9 0.4]
[4.9 3.6 1.4 0.1] [4.8 3.  1.4 0.3]
[4.9 3.6 1.4 0.1] [5.1 3.8 1.6 0.2]
[4.9 3.6 1.4 0.1] [4.6 3.2 1.4 0.2]
[4.9 3.6 1.4 0.1] [5.3 3.7 1.5 0.2]
[4.9 3.6 1.4 0.1] [5.  3.3 1.4 0.2]
[4.9 3.6 1.4 0.1] [7.  3.2 4.7 1.4]
[4.9 3.6 1.4 0.1] [6.4 3.2 4.5 1.5]
[4.9 3.6 1.4 0.1] [6.9 3.1 4.9 1.5]
[4.9 3.6 1.4 0.1] [5.5 2.3 4.  1.3]
[4.9 3.6 1.4 0.1] [6.5 2.8 4.6 1.5]
[4.9 3.6 1.4 0.1] [5.7 2.8 4.5 1.3]
[4.9 3.6 1.4 0.1] [6.3 3.3 4.7 1.6]
[4.9 3.6 1.4 0.1] [4.9 2.4 3

[5.  3.5 1.3 0.3] [5.9 3.  4.2 1.5]
[5.  3.5 1.3 0.3] [6.  2.2 4.  1. ]
[5.  3.5 1.3 0.3] [6.1 2.9 4.7 1.4]
[5.  3.5 1.3 0.3] [5.6 2.9 3.6 1.3]
[5.  3.5 1.3 0.3] [6.7 3.1 4.4 1.4]
[5.  3.5 1.3 0.3] [5.6 3.  4.5 1.5]
[5.  3.5 1.3 0.3] [5.8 2.7 4.1 1. ]
[5.  3.5 1.3 0.3] [6.2 2.2 4.5 1.5]
[5.  3.5 1.3 0.3] [5.6 2.5 3.9 1.1]
[5.  3.5 1.3 0.3] [5.9 3.2 4.8 1.8]
[5.  3.5 1.3 0.3] [6.1 2.8 4.  1.3]
[5.  3.5 1.3 0.3] [6.3 2.5 4.9 1.5]
[5.  3.5 1.3 0.3] [6.1 2.8 4.7 1.2]
[5.  3.5 1.3 0.3] [6.4 2.9 4.3 1.3]
[5.  3.5 1.3 0.3] [6.6 3.  4.4 1.4]
[5.  3.5 1.3 0.3] [6.8 2.8 4.8 1.4]
[5.  3.5 1.3 0.3] [6.7 3.  5.  1.7]
[5.  3.5 1.3 0.3] [6.  2.9 4.5 1.5]
[5.  3.5 1.3 0.3] [5.7 2.6 3.5 1. ]
[5.  3.5 1.3 0.3] [5.5 2.4 3.8 1.1]
[5.  3.5 1.3 0.3] [5.5 2.4 3.7 1. ]
[5.  3.5 1.3 0.3] [5.8 2.7 3.9 1.2]
[5.  3.5 1.3 0.3] [6.  2.7 5.1 1.6]
[5.  3.5 1.3 0.3] [5.4 3.  4.5 1.5]
[5.  3.5 1.3 0.3] [6.  3.4 4.5 1.6]
[5.  3.5 1.3 0.3] [6.7 3.1 4.7 1.5]
[5.  3.5 1.3 0.3] [6.3 2.3 4.4 1.3]
[5.  3.5 1.3 0.3] [5.6 3.  4

[5.  3.5 1.6 0.6] [7.6 3.  6.6 2.1]
[5.  3.5 1.6 0.6] [4.9 2.5 4.5 1.7]
[5.  3.5 1.6 0.6] [7.3 2.9 6.3 1.8]
[5.  3.5 1.6 0.6] [6.7 2.5 5.8 1.8]
[5.  3.5 1.6 0.6] [7.2 3.6 6.1 2.5]
[5.  3.5 1.6 0.6] [6.5 3.2 5.1 2. ]
[5.  3.5 1.6 0.6] [6.4 2.7 5.3 1.9]
[5.  3.5 1.6 0.6] [6.8 3.  5.5 2.1]
[5.  3.5 1.6 0.6] [5.7 2.5 5.  2. ]
[5.  3.5 1.6 0.6] [5.8 2.8 5.1 2.4]
[5.  3.5 1.6 0.6] [6.4 3.2 5.3 2.3]
[5.  3.5 1.6 0.6] [6.5 3.  5.5 1.8]
[5.  3.5 1.6 0.6] [7.7 3.8 6.7 2.2]
[5.  3.5 1.6 0.6] [7.7 2.6 6.9 2.3]
[5.  3.5 1.6 0.6] [6.  2.2 5.  1.5]
[5.  3.5 1.6 0.6] [6.9 3.2 5.7 2.3]
[5.  3.5 1.6 0.6] [5.6 2.8 4.9 2. ]
[5.  3.5 1.6 0.6] [7.7 2.8 6.7 2. ]
[5.  3.5 1.6 0.6] [6.3 2.7 4.9 1.8]
[5.  3.5 1.6 0.6] [6.7 3.3 5.7 2.1]
[5.  3.5 1.6 0.6] [7.2 3.2 6.  1.8]
[5.  3.5 1.6 0.6] [6.2 2.8 4.8 1.8]
[5.  3.5 1.6 0.6] [6.1 3.  4.9 1.8]
[5.  3.5 1.6 0.6] [6.4 2.8 5.6 2.1]
[5.  3.5 1.6 0.6] [7.2 3.  5.8 1.6]
[5.  3.5 1.6 0.6] [7.4 2.8 6.1 1.9]
[5.  3.5 1.6 0.6] [7.9 3.8 6.4 2. ]
[5.  3.5 1.6 0.6] [6.4 2.8 5

[5.1 3.8 1.6 0.2] [6.6 2.9 4.6 1.3]
[5.1 3.8 1.6 0.2] [5.2 2.7 3.9 1.4]
[5.1 3.8 1.6 0.2] [5.  2.  3.5 1. ]
[5.1 3.8 1.6 0.2] [5.9 3.  4.2 1.5]
[5.1 3.8 1.6 0.2] [6.  2.2 4.  1. ]
[5.1 3.8 1.6 0.2] [6.1 2.9 4.7 1.4]
[5.1 3.8 1.6 0.2] [5.6 2.9 3.6 1.3]
[5.1 3.8 1.6 0.2] [6.7 3.1 4.4 1.4]
[5.1 3.8 1.6 0.2] [5.6 3.  4.5 1.5]
[5.1 3.8 1.6 0.2] [5.8 2.7 4.1 1. ]
[5.1 3.8 1.6 0.2] [6.2 2.2 4.5 1.5]
[5.1 3.8 1.6 0.2] [5.6 2.5 3.9 1.1]
[5.1 3.8 1.6 0.2] [5.9 3.2 4.8 1.8]
[5.1 3.8 1.6 0.2] [6.1 2.8 4.  1.3]
[5.1 3.8 1.6 0.2] [6.3 2.5 4.9 1.5]
[5.1 3.8 1.6 0.2] [6.1 2.8 4.7 1.2]
[5.1 3.8 1.6 0.2] [6.4 2.9 4.3 1.3]
[5.1 3.8 1.6 0.2] [6.6 3.  4.4 1.4]
[5.1 3.8 1.6 0.2] [6.8 2.8 4.8 1.4]
[5.1 3.8 1.6 0.2] [6.7 3.  5.  1.7]
[5.1 3.8 1.6 0.2] [6.  2.9 4.5 1.5]
[5.1 3.8 1.6 0.2] [5.7 2.6 3.5 1. ]
[5.1 3.8 1.6 0.2] [5.5 2.4 3.8 1.1]
[5.1 3.8 1.6 0.2] [5.5 2.4 3.7 1. ]
[5.1 3.8 1.6 0.2] [5.8 2.7 3.9 1.2]
[5.1 3.8 1.6 0.2] [6.  2.7 5.1 1.6]
[5.1 3.8 1.6 0.2] [5.4 3.  4.5 1.5]
[5.1 3.8 1.6 0.2] [6.  3.4 4

[5.  3.3 1.4 0.2] [5.6 2.8 4.9 2. ]
[5.  3.3 1.4 0.2] [7.7 2.8 6.7 2. ]
[5.  3.3 1.4 0.2] [6.3 2.7 4.9 1.8]
[5.  3.3 1.4 0.2] [6.7 3.3 5.7 2.1]
[5.  3.3 1.4 0.2] [7.2 3.2 6.  1.8]
[5.  3.3 1.4 0.2] [6.2 2.8 4.8 1.8]
[5.  3.3 1.4 0.2] [6.1 3.  4.9 1.8]
[5.  3.3 1.4 0.2] [6.4 2.8 5.6 2.1]
[5.  3.3 1.4 0.2] [7.2 3.  5.8 1.6]
[5.  3.3 1.4 0.2] [7.4 2.8 6.1 1.9]
[5.  3.3 1.4 0.2] [7.9 3.8 6.4 2. ]
[5.  3.3 1.4 0.2] [6.4 2.8 5.6 2.2]
[5.  3.3 1.4 0.2] [6.3 2.8 5.1 1.5]
[5.  3.3 1.4 0.2] [6.1 2.6 5.6 1.4]
[5.  3.3 1.4 0.2] [7.7 3.  6.1 2.3]
[5.  3.3 1.4 0.2] [6.3 3.4 5.6 2.4]
[5.  3.3 1.4 0.2] [6.4 3.1 5.5 1.8]
[5.  3.3 1.4 0.2] [6.  3.  4.8 1.8]
[5.  3.3 1.4 0.2] [6.9 3.1 5.4 2.1]
[5.  3.3 1.4 0.2] [6.7 3.1 5.6 2.4]
[5.  3.3 1.4 0.2] [6.9 3.1 5.1 2.3]
[5.  3.3 1.4 0.2] [5.8 2.7 5.1 1.9]
[5.  3.3 1.4 0.2] [6.8 3.2 5.9 2.3]
[5.  3.3 1.4 0.2] [6.7 3.3 5.7 2.5]
[5.  3.3 1.4 0.2] [6.7 3.  5.2 2.3]
[5.  3.3 1.4 0.2] [6.3 2.5 5.  1.9]
[5.  3.3 1.4 0.2] [6.5 3.  5.2 2. ]
[5.  3.3 1.4 0.2] [6.2 3.4 5

[6.9 3.1 4.9 1.5] [5.  2.3 3.3 1. ]
[6.9 3.1 4.9 1.5] [5.6 2.7 4.2 1.3]
[6.9 3.1 4.9 1.5] [5.7 3.  4.2 1.2]
[6.9 3.1 4.9 1.5] [5.7 2.9 4.2 1.3]
[6.9 3.1 4.9 1.5] [6.2 2.9 4.3 1.3]
[6.9 3.1 4.9 1.5] [5.1 2.5 3.  1.1]
[6.9 3.1 4.9 1.5] [5.7 2.8 4.1 1.3]
[6.9 3.1 4.9 1.5] [6.3 3.3 6.  2.5]
[6.9 3.1 4.9 1.5] [5.8 2.7 5.1 1.9]
[6.9 3.1 4.9 1.5] [7.1 3.  5.9 2.1]
[6.9 3.1 4.9 1.5] [6.3 2.9 5.6 1.8]
[6.9 3.1 4.9 1.5] [6.5 3.  5.8 2.2]
[6.9 3.1 4.9 1.5] [7.6 3.  6.6 2.1]
[6.9 3.1 4.9 1.5] [4.9 2.5 4.5 1.7]
[6.9 3.1 4.9 1.5] [7.3 2.9 6.3 1.8]
[6.9 3.1 4.9 1.5] [6.7 2.5 5.8 1.8]
[6.9 3.1 4.9 1.5] [7.2 3.6 6.1 2.5]
[6.9 3.1 4.9 1.5] [6.5 3.2 5.1 2. ]
[6.9 3.1 4.9 1.5] [6.4 2.7 5.3 1.9]
[6.9 3.1 4.9 1.5] [6.8 3.  5.5 2.1]
[6.9 3.1 4.9 1.5] [5.7 2.5 5.  2. ]
[6.9 3.1 4.9 1.5] [5.8 2.8 5.1 2.4]
[6.9 3.1 4.9 1.5] [6.4 3.2 5.3 2.3]
[6.9 3.1 4.9 1.5] [6.5 3.  5.5 1.8]
[6.9 3.1 4.9 1.5] [7.7 3.8 6.7 2.2]
[6.9 3.1 4.9 1.5] [7.7 2.6 6.9 2.3]
[6.9 3.1 4.9 1.5] [6.  2.2 5.  1.5]
[6.9 3.1 4.9 1.5] [6.9 3.2 5

[6.3 3.3 4.7 1.6] [6.6 3.  4.4 1.4]
[6.3 3.3 4.7 1.6] [6.8 2.8 4.8 1.4]
[6.3 3.3 4.7 1.6] [6.7 3.  5.  1.7]
[6.3 3.3 4.7 1.6] [6.  2.9 4.5 1.5]
[6.3 3.3 4.7 1.6] [5.7 2.6 3.5 1. ]
[6.3 3.3 4.7 1.6] [5.5 2.4 3.8 1.1]
[6.3 3.3 4.7 1.6] [5.5 2.4 3.7 1. ]
[6.3 3.3 4.7 1.6] [5.8 2.7 3.9 1.2]
[6.3 3.3 4.7 1.6] [6.  2.7 5.1 1.6]
[6.3 3.3 4.7 1.6] [5.4 3.  4.5 1.5]
[6.3 3.3 4.7 1.6] [6.  3.4 4.5 1.6]
[6.3 3.3 4.7 1.6] [6.7 3.1 4.7 1.5]
[6.3 3.3 4.7 1.6] [6.3 2.3 4.4 1.3]
[6.3 3.3 4.7 1.6] [5.6 3.  4.1 1.3]
[6.3 3.3 4.7 1.6] [5.5 2.5 4.  1.3]
[6.3 3.3 4.7 1.6] [5.5 2.6 4.4 1.2]
[6.3 3.3 4.7 1.6] [6.1 3.  4.6 1.4]
[6.3 3.3 4.7 1.6] [5.8 2.6 4.  1.2]
[6.3 3.3 4.7 1.6] [5.  2.3 3.3 1. ]
[6.3 3.3 4.7 1.6] [5.6 2.7 4.2 1.3]
[6.3 3.3 4.7 1.6] [5.7 3.  4.2 1.2]
[6.3 3.3 4.7 1.6] [5.7 2.9 4.2 1.3]
[6.3 3.3 4.7 1.6] [6.2 2.9 4.3 1.3]
[6.3 3.3 4.7 1.6] [5.1 2.5 3.  1.1]
[6.3 3.3 4.7 1.6] [5.7 2.8 4.1 1.3]
[6.3 3.3 4.7 1.6] [6.3 3.3 6.  2.5]
[6.3 3.3 4.7 1.6] [5.8 2.7 5.1 1.9]
[6.3 3.3 4.7 1.6] [7.1 3.  5

[5.  2.  3.5 1. ] [4.9 3.1 1.5 0.1]
[5.  2.  3.5 1. ] [5.4 3.7 1.5 0.2]
[5.  2.  3.5 1. ] [4.8 3.4 1.6 0.2]
[5.  2.  3.5 1. ] [4.8 3.  1.4 0.1]
[5.  2.  3.5 1. ] [4.3 3.  1.1 0.1]
[5.  2.  3.5 1. ] [5.8 4.  1.2 0.2]
[5.  2.  3.5 1. ] [5.7 4.4 1.5 0.4]
[5.  2.  3.5 1. ] [5.4 3.9 1.3 0.4]
[5.  2.  3.5 1. ] [5.1 3.5 1.4 0.3]
[5.  2.  3.5 1. ] [5.7 3.8 1.7 0.3]
[5.  2.  3.5 1. ] [5.1 3.8 1.5 0.3]
[5.  2.  3.5 1. ] [5.4 3.4 1.7 0.2]
[5.  2.  3.5 1. ] [5.1 3.7 1.5 0.4]
[5.  2.  3.5 1. ] [4.6 3.6 1.  0.2]
[5.  2.  3.5 1. ] [5.1 3.3 1.7 0.5]
[5.  2.  3.5 1. ] [4.8 3.4 1.9 0.2]
[5.  2.  3.5 1. ] [5.  3.  1.6 0.2]
[5.  2.  3.5 1. ] [5.  3.4 1.6 0.4]
[5.  2.  3.5 1. ] [5.2 3.5 1.5 0.2]
[5.  2.  3.5 1. ] [5.2 3.4 1.4 0.2]
[5.  2.  3.5 1. ] [4.7 3.2 1.6 0.2]
[5.  2.  3.5 1. ] [4.8 3.1 1.6 0.2]
[5.  2.  3.5 1. ] [5.4 3.4 1.5 0.4]
[5.  2.  3.5 1. ] [5.2 4.1 1.5 0.1]
[5.  2.  3.5 1. ] [5.5 4.2 1.4 0.2]
[5.  2.  3.5 1. ] [4.9 3.1 1.5 0.2]
[5.  2.  3.5 1. ] [5.  3.2 1.2 0.2]
[5.  2.  3.5 1. ] [5.5 3.5 1

[6.  2.2 4.  1. ] [6.7 3.1 5.6 2.4]
[6.  2.2 4.  1. ] [6.9 3.1 5.1 2.3]
[6.  2.2 4.  1. ] [5.8 2.7 5.1 1.9]
[6.  2.2 4.  1. ] [6.8 3.2 5.9 2.3]
[6.  2.2 4.  1. ] [6.7 3.3 5.7 2.5]
[6.  2.2 4.  1. ] [6.7 3.  5.2 2.3]
[6.  2.2 4.  1. ] [6.3 2.5 5.  1.9]
[6.  2.2 4.  1. ] [6.5 3.  5.2 2. ]
[6.  2.2 4.  1. ] [6.2 3.4 5.4 2.3]
[6.  2.2 4.  1. ] [5.9 3.  5.1 1.8]
[6.1 2.9 4.7 1.4] [5.1 3.5 1.4 0.2]
[6.1 2.9 4.7 1.4] [4.9 3.  1.4 0.2]
[6.1 2.9 4.7 1.4] [4.7 3.2 1.3 0.2]
[6.1 2.9 4.7 1.4] [4.6 3.1 1.5 0.2]
[6.1 2.9 4.7 1.4] [5.  3.6 1.4 0.2]
[6.1 2.9 4.7 1.4] [5.4 3.9 1.7 0.4]
[6.1 2.9 4.7 1.4] [4.6 3.4 1.4 0.3]
[6.1 2.9 4.7 1.4] [5.  3.4 1.5 0.2]
[6.1 2.9 4.7 1.4] [4.4 2.9 1.4 0.2]
[6.1 2.9 4.7 1.4] [4.9 3.1 1.5 0.1]
[6.1 2.9 4.7 1.4] [5.4 3.7 1.5 0.2]
[6.1 2.9 4.7 1.4] [4.8 3.4 1.6 0.2]
[6.1 2.9 4.7 1.4] [4.8 3.  1.4 0.1]
[6.1 2.9 4.7 1.4] [4.3 3.  1.1 0.1]
[6.1 2.9 4.7 1.4] [5.8 4.  1.2 0.2]
[6.1 2.9 4.7 1.4] [5.7 4.4 1.5 0.4]
[6.1 2.9 4.7 1.4] [5.4 3.9 1.3 0.4]
[6.1 2.9 4.7 1.4] [5.1 3.5 1

[6.7 3.1 4.4 1.4] [6.7 2.5 5.8 1.8]
[6.7 3.1 4.4 1.4] [7.2 3.6 6.1 2.5]
[6.7 3.1 4.4 1.4] [6.5 3.2 5.1 2. ]
[6.7 3.1 4.4 1.4] [6.4 2.7 5.3 1.9]
[6.7 3.1 4.4 1.4] [6.8 3.  5.5 2.1]
[6.7 3.1 4.4 1.4] [5.7 2.5 5.  2. ]
[6.7 3.1 4.4 1.4] [5.8 2.8 5.1 2.4]
[6.7 3.1 4.4 1.4] [6.4 3.2 5.3 2.3]
[6.7 3.1 4.4 1.4] [6.5 3.  5.5 1.8]
[6.7 3.1 4.4 1.4] [7.7 3.8 6.7 2.2]
[6.7 3.1 4.4 1.4] [7.7 2.6 6.9 2.3]
[6.7 3.1 4.4 1.4] [6.  2.2 5.  1.5]
[6.7 3.1 4.4 1.4] [6.9 3.2 5.7 2.3]
[6.7 3.1 4.4 1.4] [5.6 2.8 4.9 2. ]
[6.7 3.1 4.4 1.4] [7.7 2.8 6.7 2. ]
[6.7 3.1 4.4 1.4] [6.3 2.7 4.9 1.8]
[6.7 3.1 4.4 1.4] [6.7 3.3 5.7 2.1]
[6.7 3.1 4.4 1.4] [7.2 3.2 6.  1.8]
[6.7 3.1 4.4 1.4] [6.2 2.8 4.8 1.8]
[6.7 3.1 4.4 1.4] [6.1 3.  4.9 1.8]
[6.7 3.1 4.4 1.4] [6.4 2.8 5.6 2.1]
[6.7 3.1 4.4 1.4] [7.2 3.  5.8 1.6]
[6.7 3.1 4.4 1.4] [7.4 2.8 6.1 1.9]
[6.7 3.1 4.4 1.4] [7.9 3.8 6.4 2. ]
[6.7 3.1 4.4 1.4] [6.4 2.8 5.6 2.2]
[6.7 3.1 4.4 1.4] [6.3 2.8 5.1 1.5]
[6.7 3.1 4.4 1.4] [6.1 2.6 5.6 1.4]
[6.7 3.1 4.4 1.4] [7.7 3.  6

[6.2 2.2 4.5 1.5] [6.3 2.8 5.1 1.5]
[6.2 2.2 4.5 1.5] [6.1 2.6 5.6 1.4]
[6.2 2.2 4.5 1.5] [7.7 3.  6.1 2.3]
[6.2 2.2 4.5 1.5] [6.3 3.4 5.6 2.4]
[6.2 2.2 4.5 1.5] [6.4 3.1 5.5 1.8]
[6.2 2.2 4.5 1.5] [6.  3.  4.8 1.8]
[6.2 2.2 4.5 1.5] [6.9 3.1 5.4 2.1]
[6.2 2.2 4.5 1.5] [6.7 3.1 5.6 2.4]
[6.2 2.2 4.5 1.5] [6.9 3.1 5.1 2.3]
[6.2 2.2 4.5 1.5] [5.8 2.7 5.1 1.9]
[6.2 2.2 4.5 1.5] [6.8 3.2 5.9 2.3]
[6.2 2.2 4.5 1.5] [6.7 3.3 5.7 2.5]
[6.2 2.2 4.5 1.5] [6.7 3.  5.2 2.3]
[6.2 2.2 4.5 1.5] [6.3 2.5 5.  1.9]
[6.2 2.2 4.5 1.5] [6.5 3.  5.2 2. ]
[6.2 2.2 4.5 1.5] [6.2 3.4 5.4 2.3]
[6.2 2.2 4.5 1.5] [5.9 3.  5.1 1.8]
[5.6 2.5 3.9 1.1] [5.1 3.5 1.4 0.2]
[5.6 2.5 3.9 1.1] [4.9 3.  1.4 0.2]
[5.6 2.5 3.9 1.1] [4.7 3.2 1.3 0.2]
[5.6 2.5 3.9 1.1] [4.6 3.1 1.5 0.2]
[5.6 2.5 3.9 1.1] [5.  3.6 1.4 0.2]
[5.6 2.5 3.9 1.1] [5.4 3.9 1.7 0.4]
[5.6 2.5 3.9 1.1] [4.6 3.4 1.4 0.3]
[5.6 2.5 3.9 1.1] [5.  3.4 1.5 0.2]
[5.6 2.5 3.9 1.1] [4.4 2.9 1.4 0.2]
[5.6 2.5 3.9 1.1] [4.9 3.1 1.5 0.1]
[5.6 2.5 3.9 1.1] [5.4 3.7 1

[6.3 2.5 4.9 1.5] [5.2 4.1 1.5 0.1]
[6.3 2.5 4.9 1.5] [5.5 4.2 1.4 0.2]
[6.3 2.5 4.9 1.5] [4.9 3.1 1.5 0.2]
[6.3 2.5 4.9 1.5] [5.  3.2 1.2 0.2]
[6.3 2.5 4.9 1.5] [5.5 3.5 1.3 0.2]
[6.3 2.5 4.9 1.5] [4.9 3.6 1.4 0.1]
[6.3 2.5 4.9 1.5] [4.4 3.  1.3 0.2]
[6.3 2.5 4.9 1.5] [5.1 3.4 1.5 0.2]
[6.3 2.5 4.9 1.5] [5.  3.5 1.3 0.3]
[6.3 2.5 4.9 1.5] [4.5 2.3 1.3 0.3]
[6.3 2.5 4.9 1.5] [4.4 3.2 1.3 0.2]
[6.3 2.5 4.9 1.5] [5.  3.5 1.6 0.6]
[6.3 2.5 4.9 1.5] [5.1 3.8 1.9 0.4]
[6.3 2.5 4.9 1.5] [4.8 3.  1.4 0.3]
[6.3 2.5 4.9 1.5] [5.1 3.8 1.6 0.2]
[6.3 2.5 4.9 1.5] [4.6 3.2 1.4 0.2]
[6.3 2.5 4.9 1.5] [5.3 3.7 1.5 0.2]
[6.3 2.5 4.9 1.5] [5.  3.3 1.4 0.2]
[6.3 2.5 4.9 1.5] [7.  3.2 4.7 1.4]
[6.3 2.5 4.9 1.5] [6.4 3.2 4.5 1.5]
[6.3 2.5 4.9 1.5] [6.9 3.1 4.9 1.5]
[6.3 2.5 4.9 1.5] [5.5 2.3 4.  1.3]
[6.3 2.5 4.9 1.5] [6.5 2.8 4.6 1.5]
[6.3 2.5 4.9 1.5] [5.7 2.8 4.5 1.3]
[6.3 2.5 4.9 1.5] [6.3 3.3 4.7 1.6]
[6.3 2.5 4.9 1.5] [4.9 2.4 3.3 1. ]
[6.3 2.5 4.9 1.5] [6.6 2.9 4.6 1.3]
[6.3 2.5 4.9 1.5] [5.2 2.7 3

[6.6 3.  4.4 1.4] [6.7 3.1 4.7 1.5]
[6.6 3.  4.4 1.4] [6.3 2.3 4.4 1.3]
[6.6 3.  4.4 1.4] [5.6 3.  4.1 1.3]
[6.6 3.  4.4 1.4] [5.5 2.5 4.  1.3]
[6.6 3.  4.4 1.4] [5.5 2.6 4.4 1.2]
[6.6 3.  4.4 1.4] [6.1 3.  4.6 1.4]
[6.6 3.  4.4 1.4] [5.8 2.6 4.  1.2]
[6.6 3.  4.4 1.4] [5.  2.3 3.3 1. ]
[6.6 3.  4.4 1.4] [5.6 2.7 4.2 1.3]
[6.6 3.  4.4 1.4] [5.7 3.  4.2 1.2]
[6.6 3.  4.4 1.4] [5.7 2.9 4.2 1.3]
[6.6 3.  4.4 1.4] [6.2 2.9 4.3 1.3]
[6.6 3.  4.4 1.4] [5.1 2.5 3.  1.1]
[6.6 3.  4.4 1.4] [5.7 2.8 4.1 1.3]
[6.6 3.  4.4 1.4] [6.3 3.3 6.  2.5]
[6.6 3.  4.4 1.4] [5.8 2.7 5.1 1.9]
[6.6 3.  4.4 1.4] [7.1 3.  5.9 2.1]
[6.6 3.  4.4 1.4] [6.3 2.9 5.6 1.8]
[6.6 3.  4.4 1.4] [6.5 3.  5.8 2.2]
[6.6 3.  4.4 1.4] [7.6 3.  6.6 2.1]
[6.6 3.  4.4 1.4] [4.9 2.5 4.5 1.7]
[6.6 3.  4.4 1.4] [7.3 2.9 6.3 1.8]
[6.6 3.  4.4 1.4] [6.7 2.5 5.8 1.8]
[6.6 3.  4.4 1.4] [7.2 3.6 6.1 2.5]
[6.6 3.  4.4 1.4] [6.5 3.2 5.1 2. ]
[6.6 3.  4.4 1.4] [6.4 2.7 5.3 1.9]
[6.6 3.  4.4 1.4] [6.8 3.  5.5 2.1]
[6.6 3.  4.4 1.4] [5.7 2.5 5

[6.  2.9 4.5 1.5] [6.4 2.8 5.6 2.2]
[6.  2.9 4.5 1.5] [6.3 2.8 5.1 1.5]
[6.  2.9 4.5 1.5] [6.1 2.6 5.6 1.4]
[6.  2.9 4.5 1.5] [7.7 3.  6.1 2.3]
[6.  2.9 4.5 1.5] [6.3 3.4 5.6 2.4]
[6.  2.9 4.5 1.5] [6.4 3.1 5.5 1.8]
[6.  2.9 4.5 1.5] [6.  3.  4.8 1.8]
[6.  2.9 4.5 1.5] [6.9 3.1 5.4 2.1]
[6.  2.9 4.5 1.5] [6.7 3.1 5.6 2.4]
[6.  2.9 4.5 1.5] [6.9 3.1 5.1 2.3]
[6.  2.9 4.5 1.5] [5.8 2.7 5.1 1.9]
[6.  2.9 4.5 1.5] [6.8 3.2 5.9 2.3]
[6.  2.9 4.5 1.5] [6.7 3.3 5.7 2.5]
[6.  2.9 4.5 1.5] [6.7 3.  5.2 2.3]
[6.  2.9 4.5 1.5] [6.3 2.5 5.  1.9]
[6.  2.9 4.5 1.5] [6.5 3.  5.2 2. ]
[6.  2.9 4.5 1.5] [6.2 3.4 5.4 2.3]
[6.  2.9 4.5 1.5] [5.9 3.  5.1 1.8]
[5.7 2.6 3.5 1. ] [5.1 3.5 1.4 0.2]
[5.7 2.6 3.5 1. ] [4.9 3.  1.4 0.2]
[5.7 2.6 3.5 1. ] [4.7 3.2 1.3 0.2]
[5.7 2.6 3.5 1. ] [4.6 3.1 1.5 0.2]
[5.7 2.6 3.5 1. ] [5.  3.6 1.4 0.2]
[5.7 2.6 3.5 1. ] [5.4 3.9 1.7 0.4]
[5.7 2.6 3.5 1. ] [4.6 3.4 1.4 0.3]
[5.7 2.6 3.5 1. ] [5.  3.4 1.5 0.2]
[5.7 2.6 3.5 1. ] [4.4 2.9 1.4 0.2]
[5.7 2.6 3.5 1. ] [4.9 3.1 1

[5.8 2.7 3.9 1.2] [5.2 4.1 1.5 0.1]
[5.8 2.7 3.9 1.2] [5.5 4.2 1.4 0.2]
[5.8 2.7 3.9 1.2] [4.9 3.1 1.5 0.2]
[5.8 2.7 3.9 1.2] [5.  3.2 1.2 0.2]
[5.8 2.7 3.9 1.2] [5.5 3.5 1.3 0.2]
[5.8 2.7 3.9 1.2] [4.9 3.6 1.4 0.1]
[5.8 2.7 3.9 1.2] [4.4 3.  1.3 0.2]
[5.8 2.7 3.9 1.2] [5.1 3.4 1.5 0.2]
[5.8 2.7 3.9 1.2] [5.  3.5 1.3 0.3]
[5.8 2.7 3.9 1.2] [4.5 2.3 1.3 0.3]
[5.8 2.7 3.9 1.2] [4.4 3.2 1.3 0.2]
[5.8 2.7 3.9 1.2] [5.  3.5 1.6 0.6]
[5.8 2.7 3.9 1.2] [5.1 3.8 1.9 0.4]
[5.8 2.7 3.9 1.2] [4.8 3.  1.4 0.3]
[5.8 2.7 3.9 1.2] [5.1 3.8 1.6 0.2]
[5.8 2.7 3.9 1.2] [4.6 3.2 1.4 0.2]
[5.8 2.7 3.9 1.2] [5.3 3.7 1.5 0.2]
[5.8 2.7 3.9 1.2] [5.  3.3 1.4 0.2]
[5.8 2.7 3.9 1.2] [7.  3.2 4.7 1.4]
[5.8 2.7 3.9 1.2] [6.4 3.2 4.5 1.5]
[5.8 2.7 3.9 1.2] [6.9 3.1 4.9 1.5]
[5.8 2.7 3.9 1.2] [5.5 2.3 4.  1.3]
[5.8 2.7 3.9 1.2] [6.5 2.8 4.6 1.5]
[5.8 2.7 3.9 1.2] [5.7 2.8 4.5 1.3]
[5.8 2.7 3.9 1.2] [6.3 3.3 4.7 1.6]
[5.8 2.7 3.9 1.2] [4.9 2.4 3.3 1. ]
[5.8 2.7 3.9 1.2] [6.6 2.9 4.6 1.3]
[5.8 2.7 3.9 1.2] [5.2 2.7 3

[6.  3.4 4.5 1.6] [5.5 2.4 3.7 1. ]
[6.  3.4 4.5 1.6] [5.8 2.7 3.9 1.2]
[6.  3.4 4.5 1.6] [6.  2.7 5.1 1.6]
[6.  3.4 4.5 1.6] [5.4 3.  4.5 1.5]
[6.  3.4 4.5 1.6] [6.  3.4 4.5 1.6]
[6.  3.4 4.5 1.6] [6.7 3.1 4.7 1.5]
[6.  3.4 4.5 1.6] [6.3 2.3 4.4 1.3]
[6.  3.4 4.5 1.6] [5.6 3.  4.1 1.3]
[6.  3.4 4.5 1.6] [5.5 2.5 4.  1.3]
[6.  3.4 4.5 1.6] [5.5 2.6 4.4 1.2]
[6.  3.4 4.5 1.6] [6.1 3.  4.6 1.4]
[6.  3.4 4.5 1.6] [5.8 2.6 4.  1.2]
[6.  3.4 4.5 1.6] [5.  2.3 3.3 1. ]
[6.  3.4 4.5 1.6] [5.6 2.7 4.2 1.3]
[6.  3.4 4.5 1.6] [5.7 3.  4.2 1.2]
[6.  3.4 4.5 1.6] [5.7 2.9 4.2 1.3]
[6.  3.4 4.5 1.6] [6.2 2.9 4.3 1.3]
[6.  3.4 4.5 1.6] [5.1 2.5 3.  1.1]
[6.  3.4 4.5 1.6] [5.7 2.8 4.1 1.3]
[6.  3.4 4.5 1.6] [6.3 3.3 6.  2.5]
[6.  3.4 4.5 1.6] [5.8 2.7 5.1 1.9]
[6.  3.4 4.5 1.6] [7.1 3.  5.9 2.1]
[6.  3.4 4.5 1.6] [6.3 2.9 5.6 1.8]
[6.  3.4 4.5 1.6] [6.5 3.  5.8 2.2]
[6.  3.4 4.5 1.6] [7.6 3.  6.6 2.1]
[6.  3.4 4.5 1.6] [4.9 2.5 4.5 1.7]
[6.  3.4 4.5 1.6] [7.3 2.9 6.3 1.8]
[6.  3.4 4.5 1.6] [6.7 2.5 5

[5.6 3.  4.1 1.3] [7.9 3.8 6.4 2. ]
[5.6 3.  4.1 1.3] [6.4 2.8 5.6 2.2]
[5.6 3.  4.1 1.3] [6.3 2.8 5.1 1.5]
[5.6 3.  4.1 1.3] [6.1 2.6 5.6 1.4]
[5.6 3.  4.1 1.3] [7.7 3.  6.1 2.3]
[5.6 3.  4.1 1.3] [6.3 3.4 5.6 2.4]
[5.6 3.  4.1 1.3] [6.4 3.1 5.5 1.8]
[5.6 3.  4.1 1.3] [6.  3.  4.8 1.8]
[5.6 3.  4.1 1.3] [6.9 3.1 5.4 2.1]
[5.6 3.  4.1 1.3] [6.7 3.1 5.6 2.4]
[5.6 3.  4.1 1.3] [6.9 3.1 5.1 2.3]
[5.6 3.  4.1 1.3] [5.8 2.7 5.1 1.9]
[5.6 3.  4.1 1.3] [6.8 3.2 5.9 2.3]
[5.6 3.  4.1 1.3] [6.7 3.3 5.7 2.5]
[5.6 3.  4.1 1.3] [6.7 3.  5.2 2.3]
[5.6 3.  4.1 1.3] [6.3 2.5 5.  1.9]
[5.6 3.  4.1 1.3] [6.5 3.  5.2 2. ]
[5.6 3.  4.1 1.3] [6.2 3.4 5.4 2.3]
[5.6 3.  4.1 1.3] [5.9 3.  5.1 1.8]
[5.5 2.5 4.  1.3] [5.1 3.5 1.4 0.2]
[5.5 2.5 4.  1.3] [4.9 3.  1.4 0.2]
[5.5 2.5 4.  1.3] [4.7 3.2 1.3 0.2]
[5.5 2.5 4.  1.3] [4.6 3.1 1.5 0.2]
[5.5 2.5 4.  1.3] [5.  3.6 1.4 0.2]
[5.5 2.5 4.  1.3] [5.4 3.9 1.7 0.4]
[5.5 2.5 4.  1.3] [4.6 3.4 1.4 0.3]
[5.5 2.5 4.  1.3] [5.  3.4 1.5 0.2]
[5.5 2.5 4.  1.3] [4.4 2.9 1

[5.8 2.6 4.  1.2] [5.  3.5 1.3 0.3]
[5.8 2.6 4.  1.2] [4.5 2.3 1.3 0.3]
[5.8 2.6 4.  1.2] [4.4 3.2 1.3 0.2]
[5.8 2.6 4.  1.2] [5.  3.5 1.6 0.6]
[5.8 2.6 4.  1.2] [5.1 3.8 1.9 0.4]
[5.8 2.6 4.  1.2] [4.8 3.  1.4 0.3]
[5.8 2.6 4.  1.2] [5.1 3.8 1.6 0.2]
[5.8 2.6 4.  1.2] [4.6 3.2 1.4 0.2]
[5.8 2.6 4.  1.2] [5.3 3.7 1.5 0.2]
[5.8 2.6 4.  1.2] [5.  3.3 1.4 0.2]
[5.8 2.6 4.  1.2] [7.  3.2 4.7 1.4]
[5.8 2.6 4.  1.2] [6.4 3.2 4.5 1.5]
[5.8 2.6 4.  1.2] [6.9 3.1 4.9 1.5]
[5.8 2.6 4.  1.2] [5.5 2.3 4.  1.3]
[5.8 2.6 4.  1.2] [6.5 2.8 4.6 1.5]
[5.8 2.6 4.  1.2] [5.7 2.8 4.5 1.3]
[5.8 2.6 4.  1.2] [6.3 3.3 4.7 1.6]
[5.8 2.6 4.  1.2] [4.9 2.4 3.3 1. ]
[5.8 2.6 4.  1.2] [6.6 2.9 4.6 1.3]
[5.8 2.6 4.  1.2] [5.2 2.7 3.9 1.4]
[5.8 2.6 4.  1.2] [5.  2.  3.5 1. ]
[5.8 2.6 4.  1.2] [5.9 3.  4.2 1.5]
[5.8 2.6 4.  1.2] [6.  2.2 4.  1. ]
[5.8 2.6 4.  1.2] [6.1 2.9 4.7 1.4]
[5.8 2.6 4.  1.2] [5.6 2.9 3.6 1.3]
[5.8 2.6 4.  1.2] [6.7 3.1 4.4 1.4]
[5.8 2.6 4.  1.2] [5.6 3.  4.5 1.5]
[5.8 2.6 4.  1.2] [5.8 2.7 4

[5.7 3.  4.2 1.2] [5.5 2.4 3.7 1. ]
[5.7 3.  4.2 1.2] [5.8 2.7 3.9 1.2]
[5.7 3.  4.2 1.2] [6.  2.7 5.1 1.6]
[5.7 3.  4.2 1.2] [5.4 3.  4.5 1.5]
[5.7 3.  4.2 1.2] [6.  3.4 4.5 1.6]
[5.7 3.  4.2 1.2] [6.7 3.1 4.7 1.5]
[5.7 3.  4.2 1.2] [6.3 2.3 4.4 1.3]
[5.7 3.  4.2 1.2] [5.6 3.  4.1 1.3]
[5.7 3.  4.2 1.2] [5.5 2.5 4.  1.3]
[5.7 3.  4.2 1.2] [5.5 2.6 4.4 1.2]
[5.7 3.  4.2 1.2] [6.1 3.  4.6 1.4]
[5.7 3.  4.2 1.2] [5.8 2.6 4.  1.2]
[5.7 3.  4.2 1.2] [5.  2.3 3.3 1. ]
[5.7 3.  4.2 1.2] [5.6 2.7 4.2 1.3]
[5.7 3.  4.2 1.2] [5.7 3.  4.2 1.2]
[5.7 3.  4.2 1.2] [5.7 2.9 4.2 1.3]
[5.7 3.  4.2 1.2] [6.2 2.9 4.3 1.3]
[5.7 3.  4.2 1.2] [5.1 2.5 3.  1.1]
[5.7 3.  4.2 1.2] [5.7 2.8 4.1 1.3]
[5.7 3.  4.2 1.2] [6.3 3.3 6.  2.5]
[5.7 3.  4.2 1.2] [5.8 2.7 5.1 1.9]
[5.7 3.  4.2 1.2] [7.1 3.  5.9 2.1]
[5.7 3.  4.2 1.2] [6.3 2.9 5.6 1.8]
[5.7 3.  4.2 1.2] [6.5 3.  5.8 2.2]
[5.7 3.  4.2 1.2] [7.6 3.  6.6 2.1]
[5.7 3.  4.2 1.2] [4.9 2.5 4.5 1.7]
[5.7 3.  4.2 1.2] [7.3 2.9 6.3 1.8]
[5.7 3.  4.2 1.2] [6.7 2.5 5

[5.1 2.5 3.  1.1] [5.  2.3 3.3 1. ]
[5.1 2.5 3.  1.1] [5.6 2.7 4.2 1.3]
[5.1 2.5 3.  1.1] [5.7 3.  4.2 1.2]
[5.1 2.5 3.  1.1] [5.7 2.9 4.2 1.3]
[5.1 2.5 3.  1.1] [6.2 2.9 4.3 1.3]
[5.1 2.5 3.  1.1] [5.1 2.5 3.  1.1]
[5.1 2.5 3.  1.1] [5.7 2.8 4.1 1.3]
[5.1 2.5 3.  1.1] [6.3 3.3 6.  2.5]
[5.1 2.5 3.  1.1] [5.8 2.7 5.1 1.9]
[5.1 2.5 3.  1.1] [7.1 3.  5.9 2.1]
[5.1 2.5 3.  1.1] [6.3 2.9 5.6 1.8]
[5.1 2.5 3.  1.1] [6.5 3.  5.8 2.2]
[5.1 2.5 3.  1.1] [7.6 3.  6.6 2.1]
[5.1 2.5 3.  1.1] [4.9 2.5 4.5 1.7]
[5.1 2.5 3.  1.1] [7.3 2.9 6.3 1.8]
[5.1 2.5 3.  1.1] [6.7 2.5 5.8 1.8]
[5.1 2.5 3.  1.1] [7.2 3.6 6.1 2.5]
[5.1 2.5 3.  1.1] [6.5 3.2 5.1 2. ]
[5.1 2.5 3.  1.1] [6.4 2.7 5.3 1.9]
[5.1 2.5 3.  1.1] [6.8 3.  5.5 2.1]
[5.1 2.5 3.  1.1] [5.7 2.5 5.  2. ]
[5.1 2.5 3.  1.1] [5.8 2.8 5.1 2.4]
[5.1 2.5 3.  1.1] [6.4 3.2 5.3 2.3]
[5.1 2.5 3.  1.1] [6.5 3.  5.5 1.8]
[5.1 2.5 3.  1.1] [7.7 3.8 6.7 2.2]
[5.1 2.5 3.  1.1] [7.7 2.6 6.9 2.3]
[5.1 2.5 3.  1.1] [6.  2.2 5.  1.5]
[5.1 2.5 3.  1.1] [6.9 3.2 5

[5.8 2.7 5.1 1.9] [6.5 3.  5.2 2. ]
[5.8 2.7 5.1 1.9] [6.2 3.4 5.4 2.3]
[5.8 2.7 5.1 1.9] [5.9 3.  5.1 1.8]
[7.1 3.  5.9 2.1] [5.1 3.5 1.4 0.2]
[7.1 3.  5.9 2.1] [4.9 3.  1.4 0.2]
[7.1 3.  5.9 2.1] [4.7 3.2 1.3 0.2]
[7.1 3.  5.9 2.1] [4.6 3.1 1.5 0.2]
[7.1 3.  5.9 2.1] [5.  3.6 1.4 0.2]
[7.1 3.  5.9 2.1] [5.4 3.9 1.7 0.4]
[7.1 3.  5.9 2.1] [4.6 3.4 1.4 0.3]
[7.1 3.  5.9 2.1] [5.  3.4 1.5 0.2]
[7.1 3.  5.9 2.1] [4.4 2.9 1.4 0.2]
[7.1 3.  5.9 2.1] [4.9 3.1 1.5 0.1]
[7.1 3.  5.9 2.1] [5.4 3.7 1.5 0.2]
[7.1 3.  5.9 2.1] [4.8 3.4 1.6 0.2]
[7.1 3.  5.9 2.1] [4.8 3.  1.4 0.1]
[7.1 3.  5.9 2.1] [4.3 3.  1.1 0.1]
[7.1 3.  5.9 2.1] [5.8 4.  1.2 0.2]
[7.1 3.  5.9 2.1] [5.7 4.4 1.5 0.4]
[7.1 3.  5.9 2.1] [5.4 3.9 1.3 0.4]
[7.1 3.  5.9 2.1] [5.1 3.5 1.4 0.3]
[7.1 3.  5.9 2.1] [5.7 3.8 1.7 0.3]
[7.1 3.  5.9 2.1] [5.1 3.8 1.5 0.3]
[7.1 3.  5.9 2.1] [5.4 3.4 1.7 0.2]
[7.1 3.  5.9 2.1] [5.1 3.7 1.5 0.4]
[7.1 3.  5.9 2.1] [4.6 3.6 1.  0.2]
[7.1 3.  5.9 2.1] [5.1 3.3 1.7 0.5]
[7.1 3.  5.9 2.1] [4.8 3.4 1

[6.5 3.  5.8 2.2] [6.  2.9 4.5 1.5]
[6.5 3.  5.8 2.2] [5.7 2.6 3.5 1. ]
[6.5 3.  5.8 2.2] [5.5 2.4 3.8 1.1]
[6.5 3.  5.8 2.2] [5.5 2.4 3.7 1. ]
[6.5 3.  5.8 2.2] [5.8 2.7 3.9 1.2]
[6.5 3.  5.8 2.2] [6.  2.7 5.1 1.6]
[6.5 3.  5.8 2.2] [5.4 3.  4.5 1.5]
[6.5 3.  5.8 2.2] [6.  3.4 4.5 1.6]
[6.5 3.  5.8 2.2] [6.7 3.1 4.7 1.5]
[6.5 3.  5.8 2.2] [6.3 2.3 4.4 1.3]
[6.5 3.  5.8 2.2] [5.6 3.  4.1 1.3]
[6.5 3.  5.8 2.2] [5.5 2.5 4.  1.3]
[6.5 3.  5.8 2.2] [5.5 2.6 4.4 1.2]
[6.5 3.  5.8 2.2] [6.1 3.  4.6 1.4]
[6.5 3.  5.8 2.2] [5.8 2.6 4.  1.2]
[6.5 3.  5.8 2.2] [5.  2.3 3.3 1. ]
[6.5 3.  5.8 2.2] [5.6 2.7 4.2 1.3]
[6.5 3.  5.8 2.2] [5.7 3.  4.2 1.2]
[6.5 3.  5.8 2.2] [5.7 2.9 4.2 1.3]
[6.5 3.  5.8 2.2] [6.2 2.9 4.3 1.3]
[6.5 3.  5.8 2.2] [5.1 2.5 3.  1.1]
[6.5 3.  5.8 2.2] [5.7 2.8 4.1 1.3]
[6.5 3.  5.8 2.2] [6.3 3.3 6.  2.5]
[6.5 3.  5.8 2.2] [5.8 2.7 5.1 1.9]
[6.5 3.  5.8 2.2] [7.1 3.  5.9 2.1]
[6.5 3.  5.8 2.2] [6.3 2.9 5.6 1.8]
[6.5 3.  5.8 2.2] [6.5 3.  5.8 2.2]
[6.5 3.  5.8 2.2] [7.6 3.  6

[6.7 2.5 5.8 1.8] [7.4 2.8 6.1 1.9]
[6.7 2.5 5.8 1.8] [7.9 3.8 6.4 2. ]
[6.7 2.5 5.8 1.8] [6.4 2.8 5.6 2.2]
[6.7 2.5 5.8 1.8] [6.3 2.8 5.1 1.5]
[6.7 2.5 5.8 1.8] [6.1 2.6 5.6 1.4]
[6.7 2.5 5.8 1.8] [7.7 3.  6.1 2.3]
[6.7 2.5 5.8 1.8] [6.3 3.4 5.6 2.4]
[6.7 2.5 5.8 1.8] [6.4 3.1 5.5 1.8]
[6.7 2.5 5.8 1.8] [6.  3.  4.8 1.8]
[6.7 2.5 5.8 1.8] [6.9 3.1 5.4 2.1]
[6.7 2.5 5.8 1.8] [6.7 3.1 5.6 2.4]
[6.7 2.5 5.8 1.8] [6.9 3.1 5.1 2.3]
[6.7 2.5 5.8 1.8] [5.8 2.7 5.1 1.9]
[6.7 2.5 5.8 1.8] [6.8 3.2 5.9 2.3]
[6.7 2.5 5.8 1.8] [6.7 3.3 5.7 2.5]
[6.7 2.5 5.8 1.8] [6.7 3.  5.2 2.3]
[6.7 2.5 5.8 1.8] [6.3 2.5 5.  1.9]
[6.7 2.5 5.8 1.8] [6.5 3.  5.2 2. ]
[6.7 2.5 5.8 1.8] [6.2 3.4 5.4 2.3]
[6.7 2.5 5.8 1.8] [5.9 3.  5.1 1.8]
[7.2 3.6 6.1 2.5] [5.1 3.5 1.4 0.2]
[7.2 3.6 6.1 2.5] [4.9 3.  1.4 0.2]
[7.2 3.6 6.1 2.5] [4.7 3.2 1.3 0.2]
[7.2 3.6 6.1 2.5] [4.6 3.1 1.5 0.2]
[7.2 3.6 6.1 2.5] [5.  3.6 1.4 0.2]
[7.2 3.6 6.1 2.5] [5.4 3.9 1.7 0.4]
[7.2 3.6 6.1 2.5] [4.6 3.4 1.4 0.3]
[7.2 3.6 6.1 2.5] [5.  3.4 1

[6.8 3.  5.5 2.1] [4.7 3.2 1.6 0.2]
[6.8 3.  5.5 2.1] [4.8 3.1 1.6 0.2]
[6.8 3.  5.5 2.1] [5.4 3.4 1.5 0.4]
[6.8 3.  5.5 2.1] [5.2 4.1 1.5 0.1]
[6.8 3.  5.5 2.1] [5.5 4.2 1.4 0.2]
[6.8 3.  5.5 2.1] [4.9 3.1 1.5 0.2]
[6.8 3.  5.5 2.1] [5.  3.2 1.2 0.2]
[6.8 3.  5.5 2.1] [5.5 3.5 1.3 0.2]
[6.8 3.  5.5 2.1] [4.9 3.6 1.4 0.1]
[6.8 3.  5.5 2.1] [4.4 3.  1.3 0.2]
[6.8 3.  5.5 2.1] [5.1 3.4 1.5 0.2]
[6.8 3.  5.5 2.1] [5.  3.5 1.3 0.3]
[6.8 3.  5.5 2.1] [4.5 2.3 1.3 0.3]
[6.8 3.  5.5 2.1] [4.4 3.2 1.3 0.2]
[6.8 3.  5.5 2.1] [5.  3.5 1.6 0.6]
[6.8 3.  5.5 2.1] [5.1 3.8 1.9 0.4]
[6.8 3.  5.5 2.1] [4.8 3.  1.4 0.3]
[6.8 3.  5.5 2.1] [5.1 3.8 1.6 0.2]
[6.8 3.  5.5 2.1] [4.6 3.2 1.4 0.2]
[6.8 3.  5.5 2.1] [5.3 3.7 1.5 0.2]
[6.8 3.  5.5 2.1] [5.  3.3 1.4 0.2]
[6.8 3.  5.5 2.1] [7.  3.2 4.7 1.4]
[6.8 3.  5.5 2.1] [6.4 3.2 4.5 1.5]
[6.8 3.  5.5 2.1] [6.9 3.1 4.9 1.5]
[6.8 3.  5.5 2.1] [5.5 2.3 4.  1.3]
[6.8 3.  5.5 2.1] [6.5 2.8 4.6 1.5]
[6.8 3.  5.5 2.1] [5.7 2.8 4.5 1.3]
[6.8 3.  5.5 2.1] [6.3 3.3 4

[6.4 3.2 5.3 2.3] [5.7 2.6 3.5 1. ]
[6.4 3.2 5.3 2.3] [5.5 2.4 3.8 1.1]
[6.4 3.2 5.3 2.3] [5.5 2.4 3.7 1. ]
[6.4 3.2 5.3 2.3] [5.8 2.7 3.9 1.2]
[6.4 3.2 5.3 2.3] [6.  2.7 5.1 1.6]
[6.4 3.2 5.3 2.3] [5.4 3.  4.5 1.5]
[6.4 3.2 5.3 2.3] [6.  3.4 4.5 1.6]
[6.4 3.2 5.3 2.3] [6.7 3.1 4.7 1.5]
[6.4 3.2 5.3 2.3] [6.3 2.3 4.4 1.3]
[6.4 3.2 5.3 2.3] [5.6 3.  4.1 1.3]
[6.4 3.2 5.3 2.3] [5.5 2.5 4.  1.3]
[6.4 3.2 5.3 2.3] [5.5 2.6 4.4 1.2]
[6.4 3.2 5.3 2.3] [6.1 3.  4.6 1.4]
[6.4 3.2 5.3 2.3] [5.8 2.6 4.  1.2]
[6.4 3.2 5.3 2.3] [5.  2.3 3.3 1. ]
[6.4 3.2 5.3 2.3] [5.6 2.7 4.2 1.3]
[6.4 3.2 5.3 2.3] [5.7 3.  4.2 1.2]
[6.4 3.2 5.3 2.3] [5.7 2.9 4.2 1.3]
[6.4 3.2 5.3 2.3] [6.2 2.9 4.3 1.3]
[6.4 3.2 5.3 2.3] [5.1 2.5 3.  1.1]
[6.4 3.2 5.3 2.3] [5.7 2.8 4.1 1.3]
[6.4 3.2 5.3 2.3] [6.3 3.3 6.  2.5]
[6.4 3.2 5.3 2.3] [5.8 2.7 5.1 1.9]
[6.4 3.2 5.3 2.3] [7.1 3.  5.9 2.1]
[6.4 3.2 5.3 2.3] [6.3 2.9 5.6 1.8]
[6.4 3.2 5.3 2.3] [6.5 3.  5.8 2.2]
[6.4 3.2 5.3 2.3] [7.6 3.  6.6 2.1]
[6.4 3.2 5.3 2.3] [4.9 2.5 4

[7.7 2.6 6.9 2.3] [7.2 3.  5.8 1.6]
[7.7 2.6 6.9 2.3] [7.4 2.8 6.1 1.9]
[7.7 2.6 6.9 2.3] [7.9 3.8 6.4 2. ]
[7.7 2.6 6.9 2.3] [6.4 2.8 5.6 2.2]
[7.7 2.6 6.9 2.3] [6.3 2.8 5.1 1.5]
[7.7 2.6 6.9 2.3] [6.1 2.6 5.6 1.4]
[7.7 2.6 6.9 2.3] [7.7 3.  6.1 2.3]
[7.7 2.6 6.9 2.3] [6.3 3.4 5.6 2.4]
[7.7 2.6 6.9 2.3] [6.4 3.1 5.5 1.8]
[7.7 2.6 6.9 2.3] [6.  3.  4.8 1.8]
[7.7 2.6 6.9 2.3] [6.9 3.1 5.4 2.1]
[7.7 2.6 6.9 2.3] [6.7 3.1 5.6 2.4]
[7.7 2.6 6.9 2.3] [6.9 3.1 5.1 2.3]
[7.7 2.6 6.9 2.3] [5.8 2.7 5.1 1.9]
[7.7 2.6 6.9 2.3] [6.8 3.2 5.9 2.3]
[7.7 2.6 6.9 2.3] [6.7 3.3 5.7 2.5]
[7.7 2.6 6.9 2.3] [6.7 3.  5.2 2.3]
[7.7 2.6 6.9 2.3] [6.3 2.5 5.  1.9]
[7.7 2.6 6.9 2.3] [6.5 3.  5.2 2. ]
[7.7 2.6 6.9 2.3] [6.2 3.4 5.4 2.3]
[7.7 2.6 6.9 2.3] [5.9 3.  5.1 1.8]
[6.  2.2 5.  1.5] [5.1 3.5 1.4 0.2]
[6.  2.2 5.  1.5] [4.9 3.  1.4 0.2]
[6.  2.2 5.  1.5] [4.7 3.2 1.3 0.2]
[6.  2.2 5.  1.5] [4.6 3.1 1.5 0.2]
[6.  2.2 5.  1.5] [5.  3.6 1.4 0.2]
[6.  2.2 5.  1.5] [5.4 3.9 1.7 0.4]
[6.  2.2 5.  1.5] [4.6 3.4 1

[7.7 2.8 6.7 2. ] [4.7 3.2 1.6 0.2]
[7.7 2.8 6.7 2. ] [4.8 3.1 1.6 0.2]
[7.7 2.8 6.7 2. ] [5.4 3.4 1.5 0.4]
[7.7 2.8 6.7 2. ] [5.2 4.1 1.5 0.1]
[7.7 2.8 6.7 2. ] [5.5 4.2 1.4 0.2]
[7.7 2.8 6.7 2. ] [4.9 3.1 1.5 0.2]
[7.7 2.8 6.7 2. ] [5.  3.2 1.2 0.2]
[7.7 2.8 6.7 2. ] [5.5 3.5 1.3 0.2]
[7.7 2.8 6.7 2. ] [4.9 3.6 1.4 0.1]
[7.7 2.8 6.7 2. ] [4.4 3.  1.3 0.2]
[7.7 2.8 6.7 2. ] [5.1 3.4 1.5 0.2]
[7.7 2.8 6.7 2. ] [5.  3.5 1.3 0.3]
[7.7 2.8 6.7 2. ] [4.5 2.3 1.3 0.3]
[7.7 2.8 6.7 2. ] [4.4 3.2 1.3 0.2]
[7.7 2.8 6.7 2. ] [5.  3.5 1.6 0.6]
[7.7 2.8 6.7 2. ] [5.1 3.8 1.9 0.4]
[7.7 2.8 6.7 2. ] [4.8 3.  1.4 0.3]
[7.7 2.8 6.7 2. ] [5.1 3.8 1.6 0.2]
[7.7 2.8 6.7 2. ] [4.6 3.2 1.4 0.2]
[7.7 2.8 6.7 2. ] [5.3 3.7 1.5 0.2]
[7.7 2.8 6.7 2. ] [5.  3.3 1.4 0.2]
[7.7 2.8 6.7 2. ] [7.  3.2 4.7 1.4]
[7.7 2.8 6.7 2. ] [6.4 3.2 4.5 1.5]
[7.7 2.8 6.7 2. ] [6.9 3.1 4.9 1.5]
[7.7 2.8 6.7 2. ] [5.5 2.3 4.  1.3]
[7.7 2.8 6.7 2. ] [6.5 2.8 4.6 1.5]
[7.7 2.8 6.7 2. ] [5.7 2.8 4.5 1.3]
[7.7 2.8 6.7 2. ] [6.3 3.3 4

[7.2 3.2 6.  1.8] [6.  2.9 4.5 1.5]
[7.2 3.2 6.  1.8] [5.7 2.6 3.5 1. ]
[7.2 3.2 6.  1.8] [5.5 2.4 3.8 1.1]
[7.2 3.2 6.  1.8] [5.5 2.4 3.7 1. ]
[7.2 3.2 6.  1.8] [5.8 2.7 3.9 1.2]
[7.2 3.2 6.  1.8] [6.  2.7 5.1 1.6]
[7.2 3.2 6.  1.8] [5.4 3.  4.5 1.5]
[7.2 3.2 6.  1.8] [6.  3.4 4.5 1.6]
[7.2 3.2 6.  1.8] [6.7 3.1 4.7 1.5]
[7.2 3.2 6.  1.8] [6.3 2.3 4.4 1.3]
[7.2 3.2 6.  1.8] [5.6 3.  4.1 1.3]
[7.2 3.2 6.  1.8] [5.5 2.5 4.  1.3]
[7.2 3.2 6.  1.8] [5.5 2.6 4.4 1.2]
[7.2 3.2 6.  1.8] [6.1 3.  4.6 1.4]
[7.2 3.2 6.  1.8] [5.8 2.6 4.  1.2]
[7.2 3.2 6.  1.8] [5.  2.3 3.3 1. ]
[7.2 3.2 6.  1.8] [5.6 2.7 4.2 1.3]
[7.2 3.2 6.  1.8] [5.7 3.  4.2 1.2]
[7.2 3.2 6.  1.8] [5.7 2.9 4.2 1.3]
[7.2 3.2 6.  1.8] [6.2 2.9 4.3 1.3]
[7.2 3.2 6.  1.8] [5.1 2.5 3.  1.1]
[7.2 3.2 6.  1.8] [5.7 2.8 4.1 1.3]
[7.2 3.2 6.  1.8] [6.3 3.3 6.  2.5]
[7.2 3.2 6.  1.8] [5.8 2.7 5.1 1.9]
[7.2 3.2 6.  1.8] [7.1 3.  5.9 2.1]
[7.2 3.2 6.  1.8] [6.3 2.9 5.6 1.8]
[7.2 3.2 6.  1.8] [6.5 3.  5.8 2.2]
[7.2 3.2 6.  1.8] [7.6 3.  6

[6.4 2.8 5.6 2.1] [6.4 2.8 5.6 2.1]
[6.4 2.8 5.6 2.1] [7.2 3.  5.8 1.6]
[6.4 2.8 5.6 2.1] [7.4 2.8 6.1 1.9]
[6.4 2.8 5.6 2.1] [7.9 3.8 6.4 2. ]
[6.4 2.8 5.6 2.1] [6.4 2.8 5.6 2.2]
[6.4 2.8 5.6 2.1] [6.3 2.8 5.1 1.5]
[6.4 2.8 5.6 2.1] [6.1 2.6 5.6 1.4]
[6.4 2.8 5.6 2.1] [7.7 3.  6.1 2.3]
[6.4 2.8 5.6 2.1] [6.3 3.4 5.6 2.4]
[6.4 2.8 5.6 2.1] [6.4 3.1 5.5 1.8]
[6.4 2.8 5.6 2.1] [6.  3.  4.8 1.8]
[6.4 2.8 5.6 2.1] [6.9 3.1 5.4 2.1]
[6.4 2.8 5.6 2.1] [6.7 3.1 5.6 2.4]
[6.4 2.8 5.6 2.1] [6.9 3.1 5.1 2.3]
[6.4 2.8 5.6 2.1] [5.8 2.7 5.1 1.9]
[6.4 2.8 5.6 2.1] [6.8 3.2 5.9 2.3]
[6.4 2.8 5.6 2.1] [6.7 3.3 5.7 2.5]
[6.4 2.8 5.6 2.1] [6.7 3.  5.2 2.3]
[6.4 2.8 5.6 2.1] [6.3 2.5 5.  1.9]
[6.4 2.8 5.6 2.1] [6.5 3.  5.2 2. ]
[6.4 2.8 5.6 2.1] [6.2 3.4 5.4 2.3]
[6.4 2.8 5.6 2.1] [5.9 3.  5.1 1.8]
[7.2 3.  5.8 1.6] [5.1 3.5 1.4 0.2]
[7.2 3.  5.8 1.6] [4.9 3.  1.4 0.2]
[7.2 3.  5.8 1.6] [4.7 3.2 1.3 0.2]
[7.2 3.  5.8 1.6] [4.6 3.1 1.5 0.2]
[7.2 3.  5.8 1.6] [5.  3.6 1.4 0.2]
[7.2 3.  5.8 1.6] [5.4 3.9 1

[6.4 2.8 5.6 2.2] [5.2 3.4 1.4 0.2]
[6.4 2.8 5.6 2.2] [4.7 3.2 1.6 0.2]
[6.4 2.8 5.6 2.2] [4.8 3.1 1.6 0.2]
[6.4 2.8 5.6 2.2] [5.4 3.4 1.5 0.4]
[6.4 2.8 5.6 2.2] [5.2 4.1 1.5 0.1]
[6.4 2.8 5.6 2.2] [5.5 4.2 1.4 0.2]
[6.4 2.8 5.6 2.2] [4.9 3.1 1.5 0.2]
[6.4 2.8 5.6 2.2] [5.  3.2 1.2 0.2]
[6.4 2.8 5.6 2.2] [5.5 3.5 1.3 0.2]
[6.4 2.8 5.6 2.2] [4.9 3.6 1.4 0.1]
[6.4 2.8 5.6 2.2] [4.4 3.  1.3 0.2]
[6.4 2.8 5.6 2.2] [5.1 3.4 1.5 0.2]
[6.4 2.8 5.6 2.2] [5.  3.5 1.3 0.3]
[6.4 2.8 5.6 2.2] [4.5 2.3 1.3 0.3]
[6.4 2.8 5.6 2.2] [4.4 3.2 1.3 0.2]
[6.4 2.8 5.6 2.2] [5.  3.5 1.6 0.6]
[6.4 2.8 5.6 2.2] [5.1 3.8 1.9 0.4]
[6.4 2.8 5.6 2.2] [4.8 3.  1.4 0.3]
[6.4 2.8 5.6 2.2] [5.1 3.8 1.6 0.2]
[6.4 2.8 5.6 2.2] [4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.2] [5.3 3.7 1.5 0.2]
[6.4 2.8 5.6 2.2] [5.  3.3 1.4 0.2]
[6.4 2.8 5.6 2.2] [7.  3.2 4.7 1.4]
[6.4 2.8 5.6 2.2] [6.4 3.2 4.5 1.5]
[6.4 2.8 5.6 2.2] [6.9 3.1 4.9 1.5]
[6.4 2.8 5.6 2.2] [5.5 2.3 4.  1.3]
[6.4 2.8 5.6 2.2] [6.5 2.8 4.6 1.5]
[6.4 2.8 5.6 2.2] [5.7 2.8 4

[7.7 3.  6.1 2.3] [6.  2.9 4.5 1.5]
[7.7 3.  6.1 2.3] [5.7 2.6 3.5 1. ]
[7.7 3.  6.1 2.3] [5.5 2.4 3.8 1.1]
[7.7 3.  6.1 2.3] [5.5 2.4 3.7 1. ]
[7.7 3.  6.1 2.3] [5.8 2.7 3.9 1.2]
[7.7 3.  6.1 2.3] [6.  2.7 5.1 1.6]
[7.7 3.  6.1 2.3] [5.4 3.  4.5 1.5]
[7.7 3.  6.1 2.3] [6.  3.4 4.5 1.6]
[7.7 3.  6.1 2.3] [6.7 3.1 4.7 1.5]
[7.7 3.  6.1 2.3] [6.3 2.3 4.4 1.3]
[7.7 3.  6.1 2.3] [5.6 3.  4.1 1.3]
[7.7 3.  6.1 2.3] [5.5 2.5 4.  1.3]
[7.7 3.  6.1 2.3] [5.5 2.6 4.4 1.2]
[7.7 3.  6.1 2.3] [6.1 3.  4.6 1.4]
[7.7 3.  6.1 2.3] [5.8 2.6 4.  1.2]
[7.7 3.  6.1 2.3] [5.  2.3 3.3 1. ]
[7.7 3.  6.1 2.3] [5.6 2.7 4.2 1.3]
[7.7 3.  6.1 2.3] [5.7 3.  4.2 1.2]
[7.7 3.  6.1 2.3] [5.7 2.9 4.2 1.3]
[7.7 3.  6.1 2.3] [6.2 2.9 4.3 1.3]
[7.7 3.  6.1 2.3] [5.1 2.5 3.  1.1]
[7.7 3.  6.1 2.3] [5.7 2.8 4.1 1.3]
[7.7 3.  6.1 2.3] [6.3 3.3 6.  2.5]
[7.7 3.  6.1 2.3] [5.8 2.7 5.1 1.9]
[7.7 3.  6.1 2.3] [7.1 3.  5.9 2.1]
[7.7 3.  6.1 2.3] [6.3 2.9 5.6 1.8]
[7.7 3.  6.1 2.3] [6.5 3.  5.8 2.2]
[7.7 3.  6.1 2.3] [7.6 3.  6

[6.  3.  4.8 1.8] [6.1 3.  4.9 1.8]
[6.  3.  4.8 1.8] [6.4 2.8 5.6 2.1]
[6.  3.  4.8 1.8] [7.2 3.  5.8 1.6]
[6.  3.  4.8 1.8] [7.4 2.8 6.1 1.9]
[6.  3.  4.8 1.8] [7.9 3.8 6.4 2. ]
[6.  3.  4.8 1.8] [6.4 2.8 5.6 2.2]
[6.  3.  4.8 1.8] [6.3 2.8 5.1 1.5]
[6.  3.  4.8 1.8] [6.1 2.6 5.6 1.4]
[6.  3.  4.8 1.8] [7.7 3.  6.1 2.3]
[6.  3.  4.8 1.8] [6.3 3.4 5.6 2.4]
[6.  3.  4.8 1.8] [6.4 3.1 5.5 1.8]
[6.  3.  4.8 1.8] [6.  3.  4.8 1.8]
[6.  3.  4.8 1.8] [6.9 3.1 5.4 2.1]
[6.  3.  4.8 1.8] [6.7 3.1 5.6 2.4]
[6.  3.  4.8 1.8] [6.9 3.1 5.1 2.3]
[6.  3.  4.8 1.8] [5.8 2.7 5.1 1.9]
[6.  3.  4.8 1.8] [6.8 3.2 5.9 2.3]
[6.  3.  4.8 1.8] [6.7 3.3 5.7 2.5]
[6.  3.  4.8 1.8] [6.7 3.  5.2 2.3]
[6.  3.  4.8 1.8] [6.3 2.5 5.  1.9]
[6.  3.  4.8 1.8] [6.5 3.  5.2 2. ]
[6.  3.  4.8 1.8] [6.2 3.4 5.4 2.3]
[6.  3.  4.8 1.8] [5.9 3.  5.1 1.8]
[6.9 3.1 5.4 2.1] [5.1 3.5 1.4 0.2]
[6.9 3.1 5.4 2.1] [4.9 3.  1.4 0.2]
[6.9 3.1 5.4 2.1] [4.7 3.2 1.3 0.2]
[6.9 3.1 5.4 2.1] [4.6 3.1 1.5 0.2]
[6.9 3.1 5.4 2.1] [5.  3.6 1

[5.8 2.7 5.1 1.9] [5.2 3.5 1.5 0.2]
[5.8 2.7 5.1 1.9] [5.2 3.4 1.4 0.2]
[5.8 2.7 5.1 1.9] [4.7 3.2 1.6 0.2]
[5.8 2.7 5.1 1.9] [4.8 3.1 1.6 0.2]
[5.8 2.7 5.1 1.9] [5.4 3.4 1.5 0.4]
[5.8 2.7 5.1 1.9] [5.2 4.1 1.5 0.1]
[5.8 2.7 5.1 1.9] [5.5 4.2 1.4 0.2]
[5.8 2.7 5.1 1.9] [4.9 3.1 1.5 0.2]
[5.8 2.7 5.1 1.9] [5.  3.2 1.2 0.2]
[5.8 2.7 5.1 1.9] [5.5 3.5 1.3 0.2]
[5.8 2.7 5.1 1.9] [4.9 3.6 1.4 0.1]
[5.8 2.7 5.1 1.9] [4.4 3.  1.3 0.2]
[5.8 2.7 5.1 1.9] [5.1 3.4 1.5 0.2]
[5.8 2.7 5.1 1.9] [5.  3.5 1.3 0.3]
[5.8 2.7 5.1 1.9] [4.5 2.3 1.3 0.3]
[5.8 2.7 5.1 1.9] [4.4 3.2 1.3 0.2]
[5.8 2.7 5.1 1.9] [5.  3.5 1.6 0.6]
[5.8 2.7 5.1 1.9] [5.1 3.8 1.9 0.4]
[5.8 2.7 5.1 1.9] [4.8 3.  1.4 0.3]
[5.8 2.7 5.1 1.9] [5.1 3.8 1.6 0.2]
[5.8 2.7 5.1 1.9] [4.6 3.2 1.4 0.2]
[5.8 2.7 5.1 1.9] [5.3 3.7 1.5 0.2]
[5.8 2.7 5.1 1.9] [5.  3.3 1.4 0.2]
[5.8 2.7 5.1 1.9] [7.  3.2 4.7 1.4]
[5.8 2.7 5.1 1.9] [6.4 3.2 4.5 1.5]
[5.8 2.7 5.1 1.9] [6.9 3.1 4.9 1.5]
[5.8 2.7 5.1 1.9] [5.5 2.3 4.  1.3]
[5.8 2.7 5.1 1.9] [6.5 2.8 4

[6.7 3.  5.2 2.3] [6.7 3.  5.  1.7]
[6.7 3.  5.2 2.3] [6.  2.9 4.5 1.5]
[6.7 3.  5.2 2.3] [5.7 2.6 3.5 1. ]
[6.7 3.  5.2 2.3] [5.5 2.4 3.8 1.1]
[6.7 3.  5.2 2.3] [5.5 2.4 3.7 1. ]
[6.7 3.  5.2 2.3] [5.8 2.7 3.9 1.2]
[6.7 3.  5.2 2.3] [6.  2.7 5.1 1.6]
[6.7 3.  5.2 2.3] [5.4 3.  4.5 1.5]
[6.7 3.  5.2 2.3] [6.  3.4 4.5 1.6]
[6.7 3.  5.2 2.3] [6.7 3.1 4.7 1.5]
[6.7 3.  5.2 2.3] [6.3 2.3 4.4 1.3]
[6.7 3.  5.2 2.3] [5.6 3.  4.1 1.3]
[6.7 3.  5.2 2.3] [5.5 2.5 4.  1.3]
[6.7 3.  5.2 2.3] [5.5 2.6 4.4 1.2]
[6.7 3.  5.2 2.3] [6.1 3.  4.6 1.4]
[6.7 3.  5.2 2.3] [5.8 2.6 4.  1.2]
[6.7 3.  5.2 2.3] [5.  2.3 3.3 1. ]
[6.7 3.  5.2 2.3] [5.6 2.7 4.2 1.3]
[6.7 3.  5.2 2.3] [5.7 3.  4.2 1.2]
[6.7 3.  5.2 2.3] [5.7 2.9 4.2 1.3]
[6.7 3.  5.2 2.3] [6.2 2.9 4.3 1.3]
[6.7 3.  5.2 2.3] [5.1 2.5 3.  1.1]
[6.7 3.  5.2 2.3] [5.7 2.8 4.1 1.3]
[6.7 3.  5.2 2.3] [6.3 3.3 6.  2.5]
[6.7 3.  5.2 2.3] [5.8 2.7 5.1 1.9]
[6.7 3.  5.2 2.3] [7.1 3.  5.9 2.1]
[6.7 3.  5.2 2.3] [6.3 2.9 5.6 1.8]
[6.7 3.  5.2 2.3] [6.5 3.  5

[6.2 3.4 5.4 2.3] [6.5 3.2 5.1 2. ]
[6.2 3.4 5.4 2.3] [6.4 2.7 5.3 1.9]
[6.2 3.4 5.4 2.3] [6.8 3.  5.5 2.1]
[6.2 3.4 5.4 2.3] [5.7 2.5 5.  2. ]
[6.2 3.4 5.4 2.3] [5.8 2.8 5.1 2.4]
[6.2 3.4 5.4 2.3] [6.4 3.2 5.3 2.3]
[6.2 3.4 5.4 2.3] [6.5 3.  5.5 1.8]
[6.2 3.4 5.4 2.3] [7.7 3.8 6.7 2.2]
[6.2 3.4 5.4 2.3] [7.7 2.6 6.9 2.3]
[6.2 3.4 5.4 2.3] [6.  2.2 5.  1.5]
[6.2 3.4 5.4 2.3] [6.9 3.2 5.7 2.3]
[6.2 3.4 5.4 2.3] [5.6 2.8 4.9 2. ]
[6.2 3.4 5.4 2.3] [7.7 2.8 6.7 2. ]
[6.2 3.4 5.4 2.3] [6.3 2.7 4.9 1.8]
[6.2 3.4 5.4 2.3] [6.7 3.3 5.7 2.1]
[6.2 3.4 5.4 2.3] [7.2 3.2 6.  1.8]
[6.2 3.4 5.4 2.3] [6.2 2.8 4.8 1.8]
[6.2 3.4 5.4 2.3] [6.1 3.  4.9 1.8]
[6.2 3.4 5.4 2.3] [6.4 2.8 5.6 2.1]
[6.2 3.4 5.4 2.3] [7.2 3.  5.8 1.6]
[6.2 3.4 5.4 2.3] [7.4 2.8 6.1 1.9]
[6.2 3.4 5.4 2.3] [7.9 3.8 6.4 2. ]
[6.2 3.4 5.4 2.3] [6.4 2.8 5.6 2.2]
[6.2 3.4 5.4 2.3] [6.3 2.8 5.1 1.5]
[6.2 3.4 5.4 2.3] [6.1 2.6 5.6 1.4]
[6.2 3.4 5.4 2.3] [7.7 3.  6.1 2.3]
[6.2 3.4 5.4 2.3] [6.3 3.4 5.6 2.4]
[6.2 3.4 5.4 2.3] [6.4 3.1 5

In [29]:
for row1 in data:
    row=[]
    for row2 in data:
        row.append(sum((row1-row2)**2)**(1/2))
    dist.append(row)

In [ ]:
# another import (usually all imports are done at the top of the script/ notebook)
import seaborn as sns

In [ ]:
sns.heatmap(dist)

# Plotting data: 
Don't worry about the code as that's not the objective of the exercise and we will learn how to plot data in future classes
### How can we represent an observation in a N-dimensional Space

In [ ]:
# another import (usually all imports are done at the top of the script/ notebook)
import matplotlib.pyplot as plt

In [ ]:
# 2D scatter plot
plt.scatter(data[:, 0], data[:, 1])
plt.xlabel(dataset["feature_names"][0])
plt.ylabel(dataset["feature_names"][1])
plt.show()

In [ ]:
# 1D scatter plot
plt.scatter(data[:, 0], [0 for i in range(data.shape[0])])
plt.xlabel(dataset["feature_names"][0])
plt.show()

In [ ]:
# 3D scatter plot
fig = plt.figure(figsize=(14, 7))  # defining a figure so we can add a 3d subplot
ax = fig.add_subplot(111, projection="3d")
ax.scatter(data[:, 0], data[:, 1], data[:, 2])
ax.set_xlabel(dataset["feature_names"][0])
ax.set_ylabel(dataset["feature_names"][1])
ax.set_zlabel(dataset["feature_names"][2])
plt.show()

## Finding nearest neighbors

In [ ]:
# get variables to save closest neighbors later
min_args, min_dist = (None, 9e99)
for id_r, row in enumerate(dist):
    # CODE HERE


In [ ]:
min_args

In [ ]:
print(data[min_args[0]])
print(data[min_args[1]])
print('minimum distance:\t', min_dist)

## Define functions
Why do we want to define functions in this case?

In [ ]:
def distance_matrix(data):
    # CODE HERE
    return dist    

def closest_points(dist_matrix):
    # CODE HERE
    return min_args, min_dist

## Finding the `n` shortest distances

In [ ]:
dist_matrix = distance_matrix(data)
n_distances = 10

# CODE HERE

distances